name:                try-moffy
version:             0.1.0.1
github:              "YoshikuniJujo/try-moffy"
license:             BSD3
author:              "Yoshikuni Jujo"
maintainer:          "PAF01143@nifty.ne.jp"
copyright:           "Yoshikuni Jujo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/try-moffy#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- random
- simple-field
- extra-data-yj
- time
- transformers
- monads-tf
- type-flip
- bytestring
- text
- JuicyPixels
- JuicyPixels-extra
- aeson
- X11-xft
- http-conduit
- vector
- process
- unordered-containers
- X11
- stm
- containers
- serialise
- exception-hierarchy
- simple-cairo
- simple-gdk3
- x-keysym
- union-color
- GLFW-b

library:
  source-dirs: src
  pkg-config-dependencies: gtk+-3.0
  include-dirs: include

executables:
  try-moffy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  followbox:
    main:                followbox.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  followboxGtk:
    main:                followboxGtk.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  tryGtk:
    main:                tryGtk.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  tryCairo:
    main:                tryCairo.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  tryCairoText:
    main:                tryCairoText.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  tryPango:
    main:                tryPango.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  tryCairoTextExtents:
    main:                tryCairoTextExtents.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  draw :
    main:                draw.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  tryFillPolygon :
    main:                tryFillPolygon.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  tryScroll :
    main:                tryScroll.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  tryMultiWindow:
    main:                tryMultiWindow.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  tryDefaultWindow:
    main:                tryDefaultWindow.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  tryCount:
    main:                tryCount.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  tryConfigure:
    main:                tryConfigure.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  tryPngCursor:
    main:                tryPngCursor.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  tryPngCursorEvent:
    main:                tryPngCursorEvent.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  tryDeleteEvent:
    main:                tryDeleteEvent.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  tryKey:
    main:                tryKey.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  tryGdk:
    main:                tryGdk.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  try-gdk-boxes:
    main:                try-gdk-boxes.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  try-gdk-gui:
    main:                try-gdk-gui.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
  try-glfw-boxes:
    main:                try-glfw-boxes.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy

tests:
  try-moffy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy
