name:                try-gpu-vulkan-khr-swapchain
version:             0.1.0.0
github:              "githubuser/try-gpu-vulkan-khr-swapchain"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-gpu-vulkan-khr-swapchain#readme>

dependencies:
- base >= 4.7 && < 5
- stm
- containers
- gpu-vulkan
- gpu-vulkan-khr-surface
- gpu-vulkan-middle-khr-swapchain
- hetero-parameter-list
- storable-peek-poke
- typelevel-tools-yj
- fixed-generic

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Gpu.Vulkan.Khr.Swapchain

tests:
  try-gpu-vulkan-khr-swapchain-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gpu-vulkan-khr-swapchain
