name:                try-concurrent-zundoko
version:             0.1.0.0
github:              "githubuser/try-concurrent-zundoko"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-concurrent-zundoko#readme>

dependencies:
- base >= 4.7 && < 5
- ghc-heap
- stm
- random

library:
  source-dirs: src

executables:
  try-concurrent-zundoko-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-concurrent-zundoko
  zundoko2:
    main:                zundoko2.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-concurrent-zundoko
  zundoko3:
    main:                zundoko3.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-concurrent-zundoko
  zundoko4:
    main:                zundoko4.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-concurrent-zundoko
  zundoko5:
    main:                zundoko5.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-concurrent-zundoko
  ppap:
    main:                ppap.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-concurrent-zundoko
  scat:
    main:                scat.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-concurrent-zundoko

tests:
  try-concurrent-zundoko-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-concurrent-zundoko
