name:                tools-yj
version:             0.1.0.19
github:              "YoshikuniJujo/tools-yj"
license:             BSD-3-Clause
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "Copyright (c) 2023 Yoshikuni Jujo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/tools-yj#readme>

dependencies:
- base >= 4.7 && < 5
- mono-traversable < 2
- stm < 3
- containers < 1
- text < 3
- data-default < 1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  tools-yj-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tools-yj
