name:                bug-pattern-synonym-haddock
version:             0.1.0.0
github:              "YoshikuniJujo/try-moffy"
license:             BSD3
author:              "Yoshikuni Jujo"
maintainer:          "PAF01143@nifty.ne.jp"
copyright:           "Yoshikuni Jujo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/try-moffy#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
