name:                try-lifegame-simple
version:             0.1.0.0
github:              "YoshikuniJujo/try-lifegame-simple"
license:             BSD-3-Clause
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "(c) 2025 Yoshikuni Jujo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/try-lifegame-simple#readme>

dependencies:
- base >= 4.7 && < 5
- deepseq
- mono-traversable
- vector
- bytestring
- bytestring-ft
- directory
- filepath
- yaftee
- yaftee-basic-monads
- yaftee-conduit
- yaftee-conduit-bytestring
- higher-order-open-union
- png-chunk-yaftee
- zlib-yaftee
- zlib-core
- tools-yj

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  try-lifegame-ng:
    main:                try-lifegame-ng.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-lifegame-simple
  try-readchunk-ng:
    main:                try-readchunk-ng.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-lifegame-simple

tests:
  try-lifegame-simple-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-lifegame-simple
