name:                try-imgui-sample
version:             0.1.0.0
github:              "YoshikuniJujo/try-imgui-sample"
license:             BSD-3-Clause
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "(c) 2025 Yoshikuni Jujo"

extra-doc-files:
- README.md
- CHANGELOG.md

extra-source-files:
- include/imgui.h
- include/imgui_c.h
- include/imconfig.h
- include/imgui_internal.h
- include/imstb_rectpack.h
- include/imstb_textedit.h
- include/imstb_truetype.h
- include/backends/imgui_impl_glfw.h
- include/backends/imgui_impl_vulkan.h
- include/helper/imgui_impl_vulkan_helper_c.h
- flags/appUseUnlimitedFrameRate/AppUseUnlimitedFrameRate.hs
- flags/noAppUseUnlimitedFrameRate/AppUseUnlimitedFrameRate.hs

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/try-imgui-sample#readme>

flags:
  debug:
    manual: true
    default: true
  oldLog:
    manual: true
    default: false
  appUseUnlimitedFrameRate:
    manual: true
    default: false

dependencies:
- base >= 4.7 && < 5
- primitive
- bytestring
- text
- data-default
- c-struct
- c-enum
- gpu-vulkan
- gpu-vulkan-khr-swapchain
- gpu-vulkan-khr-surface
- gpu-vulkan-khr-surface-glfw
- try-gpu-vulkan-ext-debug-utils
- gpu-vulkan-middle
- gpu-vulkan-middle-khr-swapchain
- gpu-vulkan-middle-khr-surface
- gpu-vulkan-core
- gpu-vulkan-core-khr-swapchain
- gpu-vulkan-core-khr-surface
- glfw-group
- GLFW-b
- bindings-GLFW
- hetero-parameter-list
- storable-peek-poke
- tools-yj
- typelevel-tools-yj

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  when:
    - condition: flag(debug)
      then:
        source-dirs: flags/debug
        exposed-modules: Debug
      else:
        source-dirs: flags/nodebug
        exposed-modules: Debug
    - condition: flag(oldLog)
      then:
        source-dirs: flags/oldLog
        exposed-modules: OldLog
      else:
        source-dirs: flags/noOldLog
        exposed-modules: OldLog
    - condition: flag(appUseUnlimitedFrameRate)
      then:
        source-dirs: flags/appUseUnlimitedFrameRate
        exposed-modules: AppUseUnlimitedFrameRate
      else:
        source-dirs: flags/noAppUseUnlimitedFrameRate
        exposed-modules: AppUseUnlimitedFrameRate
  extra-libraries: stdc++
  pkg-config-dependencies:
    - vulkan
    - glfw3

cxx-sources:
  - cxxsrc/main.cpp
  - cxxsrc/imgui.cpp
  - cxxsrc/imgui_extern_c.cpp
  - cxxsrc/imgui_draw.cpp
  - cxxsrc/imgui_widgets.cpp
  - cxxsrc/imgui_tables.cpp
  - cxxsrc/imgui_demo.cpp
  - cxxsrc/backends/imgui_impl_glfw.cpp
  - cxxsrc/backends/imgui_impl_vulkan.cpp
  - cxxsrc/trans/helper/imgui_implvulkanh_window.cpp

include-dirs:
  - include/
  - include/backends
  - include/helper

executables:
  try-imgui-sample-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-imgui-sample
  trySome:
    main:                trySome.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-imgui-sample

tests:
  try-imgui-sample-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-imgui-sample
