name:                life-hierarchy
version:             0.1.0.0
github:              "YoshikuniJujo/life-hierarchy"
license:             BSD3
author:              "Yoshikuni Jujo"
maintainer:          "PAF01143@nifty.ne.jp"
copyright:           "Yoshikuni Jujo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/life-hierarchy#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- exception-hierarchy

library:
  source-dirs: src

executables:
  life-hierarchy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - life-hierarchy

tests:
  life-hierarchy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - life-hierarchy
