name:                try-vulkan-graphics
version:             0.1.0.0
github:              "githubuser/try-vulkan-graphics"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md
- debug/Debug.hs
- nodebug/Debug.hs

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-vulkan-graphics#readme>

flags:
  debug:
    manual: true
    default: true

dependencies:
- base >= 4.7 && < 5
- template-haskell
- stm
- mtl
- random
- bytestring
- data-default
- containers
- array
- vector
- text
- time
- JuicyPixels
- GLFW-b
- optparse-declarative
- gpu-vulkan
- gpu-vulkan-khr-swapchain
- gpu-vulkan-khr-surface
- gpu-vulkan-khr-surface-glfw
- try-gpu-vulkan-ext-debug-utils
- try-gpu-vulkan-cglm
- glfw-group
- language-spir-v
- shaderc
- hetero-parameter-list
- storable-peek-poke
- storable-generic
- union-color
- ranged-list
- typelevel-tools-yj
- temporary
- tools-yj
- mono-traversable
- extra-data-yj

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  when:
    - condition: flag(debug)
      then:
        source-dirs: debug
        exposed-modules:
          - Debug
      else:
        source-dirs: nodebug
        exposed-modules:
          - Debug

data-files:
  - shader/expandWidth.comp
  - shader/expandHeight.comp
  - shader/interpolate.comp
  - shader/interpolate_float_bug.comp

executables:
  try-triangle-single:
    main:                try-triangle-single.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
  try-rectangle-single:
    main:                try-rectangle-single.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
  try-cube-single:
    main:                try-cube-single.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
  try-gamepad-button:
    main:                try-gamepad-button.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
  try-multiple-windows:
    main:                try-multiple-windows.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
  try-depth-buffering-single:
    main:                try-depth-buffering-single.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
  try-point-rectangle-single:
    main:                try-point-rectangle-single.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
  try-compute:
    main:                try-compute.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
  try-vulkan-guide-initializing:
    main:                try-vulkan-guide-initializing.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
  try-vulkan-guide-drawing-with-compute:
    main:                try-vulkan-guide-drawing-with-compute.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
  bicubic-interpolation:
    main:                bicubic-interpolation.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
  bicubic-interpolation-float-bug:
    main:                bicubic-interpolation-float-bug.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics

tests:
  try-vulkan-graphics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
