name:                try-vulkan-graphics
version:             0.1.0.0
github:              "githubuser/try-vulkan-graphics"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-vulkan-graphics#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- data-default
- containers
- vector
- text
- time
- JuicyPixels
- GLFW-b
- try-gpu-vulkan
- try-gpu-vulkan-khr
- try-gpu-vulkan-khr-glfw
- try-gpu-vulkan-ext-debug-utils
- try-gpu-vulkan-cglm
- try-language-spir-v
- try-shaderc
- size-alignment-list
- try-hetero-parameter-list
- try-storable-peek-poke
- try-storable-generic
- union-color
- ranged-list
- typelevel-tools
- temporary

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  try-triangle-single:
    main:                try-triangle-single.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
  try-rectangle-single:
    main:                try-rectangle-single.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
  try-cube-single:
    main:                try-cube-single.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
  try-pyramid-single:
    main:                try-pyramid-single.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
  try-gamepad-button:
    main:                try-gamepad-button.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
  try-multi-rectangles:
    main:                try-multi-rectangles.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics

tests:
  try-vulkan-graphics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-graphics
