-- This file is automatically generated by the tools/makeEnum.hs
--	% stack runghc --cwd tools/ makeEnum

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Vulkan.Descriptor.Enum where

import Foreign.Storable
import Foreign.C.Enum
import Data.Word

#include <vulkan/vulkan.h>

enum "Type" ''#{type VkDescriptorType}
		[''Show, ''Eq, ''Storable] [
	("TypeSampler", #{const VK_DESCRIPTOR_TYPE_SAMPLER}),
	("TypeCombinedImageSampler",
		#{const VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER}),
	("TypeSampledImage",
		#{const VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE}),
	("TypeStorageImage",
		#{const VK_DESCRIPTOR_TYPE_STORAGE_IMAGE}),
	("TypeUniformTexelBuffer",
		#{const VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER}),
	("TypeStorageTexelBuffer",
		#{const VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER}),
	("TypeUniformBuffer",
		#{const VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER}),
	("TypeStorageBuffer",
		#{const VK_DESCRIPTOR_TYPE_STORAGE_BUFFER}),
	("TypeUniformBufferDynamic",
		#{const VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC}),
	("TypeStorageBufferDynamic",
		#{const VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC}),
	("TypeInputAttachment",
		#{const VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT}),
	("TypeInlineUniformBlock",
		#{const VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK}),
	("TypeAccelerationStructureKhr",
		#{const VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR}),
	("TypeAccelerationStructureNv",
		#{const VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV}),
	("TypeMutableValve",
		#{const VK_DESCRIPTOR_TYPE_MUTABLE_VALVE}),
	("TypeInlineUniformBlockExt",
		#{const VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK_EXT}),
	("TypeMaxEnum", #{const VK_DESCRIPTOR_TYPE_MAX_ENUM}) ]
