name:                try-monadic-functional-reactive-programming
version:             0.1.0.0
github:              "githubuser/try-monadic-functional-reactive-programming"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-monadic-functional-reactive-programming#readme>

dependencies:
- base >= 4.7 && < 5
- stm
- monads-tf
- monad-control
- bytestring
- text
- containers
- time
- X11
- utf8-string
- http-conduit
- aeson

library:
  source-dirs: src

executables:
  try-monadic-functional-reactive-programming-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-delta-time:
    main:                tryDeltaTime.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-sleep:
    main:                trySleep.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-same-click:
    main:                trySameClick.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-doubler:
    main:                tryDoubler.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-cycle-color:
    main:                tryCycleColor.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-mouse-pos:
    main:                tryMousePos.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-cur-rect:
    main:                tryCurRect.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-elapsed:
    main:                tryElapsed.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-wiggle-rect:
    main:                tryWiggleRect.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-pos-inside:
    main:                tryPosInside.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-first-point:
    main:                tryFirstPoint.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-complete-rect:
    main:                tryCompleteRect.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-define-rect:
    main:                tryDefineRect.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-choose-box-color:
    main:                tryChooseBoxColor.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-dr-click-on:
    main:                tryDrClickOn.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-box:
    main:                tryBox.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-boxes:
    main:                tryBoxes.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-check-dup:
    main:                tryCheckDup.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-get-users-byte-string:
    main:                tryGetUsersByteString.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-get-users-json:
    main:                tryGetUsersJson.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
  try-prod-user:
    main:                tryProdUser.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming

tests:
  try-monadic-functional-reactive-programming-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-monadic-functional-reactive-programming
