-- This file is automatically generated by the tools/makeEnum.hs
--	% stack runghc --cwd tools/ makeEnum

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeSynonymInstances #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Gpu.Vulkan.Queue.Enum where

import Foreign.Storable
import Foreign.C.Enum
import Data.Bits
import Data.Word

#include <vulkan/vulkan.h>

enum "FlagBits" ''#{type VkQueueFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits, ''FiniteBits] [
	("FlagsZero", 0),
	("GraphicsBit", #{const VK_QUEUE_GRAPHICS_BIT}),
	("ComputeBit", #{const VK_QUEUE_COMPUTE_BIT}),
	("TransferBit", #{const VK_QUEUE_TRANSFER_BIT}),
	("SparseBindingBit", #{const VK_QUEUE_SPARSE_BINDING_BIT}),
	("ProtectedBit", #{const VK_QUEUE_PROTECTED_BIT}),
	("FlagBitsMaxEnum", #{const VK_QUEUE_FLAG_BITS_MAX_ENUM}) ]

type Flags = FlagBits
