name:                try-my-vulkan-snd
version:             0.1.0.0
github:              "githubuser/try-my-vulkan-snd"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-my-vulkan-snd#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- containers
- bytestring
- text
- monads-tf
- filepath
- nowdoc
- exception-hierarchy
- c-enum
- c-struct
- uuid
- GLFW-b
- ranged-list
- try-shaderc
- try-pointable
- size-alignment-list
- union-color

library:
  source-dirs: src
  pkg-config-dependencies:
  - vulkan

data-files:
  - th/vkPhysicalDeviceLimits.txt

executables:
  try-my-vulkan-snd-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-next-triangle:
    main:                try-next-triangle.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-shaderc-core:
    main:                try-shaderc-core.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-shaderc:
    main:                try-shaderc.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  my-glslc:
    main:                my-glslc.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd

tests:
  try-my-vulkan-snd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
