name:                try-my-vulkan-snd
version:             0.1.0.0
github:              "githubuser/try-my-vulkan-snd"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-my-vulkan-snd#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- containers
- array
- bytestring
- text
- monads-tf
- filepath
- JuicyPixels
- vector
- nowdoc
- exception-hierarchy
- c-enum
- c-struct
- uuid
- GLFW-b
- ranged-list
- try-shaderc
- try-pointable
- size-alignment-list
- union-color
- ghc-prim
- time
- mono-traversable
- data-default
- try-vulkan-core
- try-vulkan-core-khr
- try-vulkan-core-ext-debug-utils

library:
  source-dirs: src

data-files:
  - th/vkPhysicalDeviceLimits.txt
  - th/vkPhysicalDeviceFeatures.txt

executables:
  try-next-triangle:
    main:                try-next-triangle.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-triangle-single:
    main:                try-triangle-single.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-rectangle:
    main:                try-rectangle.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-rectangle-single:
    main:                try-rectangle-single.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-texture-single:
    main:                try-texture-single.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-texture:
    main:                try-texture.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-depth-buffering-single:
    main:                try-depth-buffering-single.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-depth-buffering:
    main:                try-depth-buffering.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-loading-models-single:
    main:                try-loading-models-single.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-loading-models:
    main:                try-loading-models.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-generating-mipmaps-single:
    main:                try-generating-mipmaps-single.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-generating-mipmaps:
    main:                try-generating-mipmaps.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-multisampling-single:
    main:                try-multisampling-single.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-multisampling:
    main:                try-multisampling.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-shaderc-core:
    main:                try-shaderc-core.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-shaderc:
    main:                try-shaderc.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  my-glslc:
    main:                my-glslc.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-vertex-input-state:
    main:                try-vertex-input-state.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-yatteiku:
    main:                try-yatteiku.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-saitan:
    main:                try-saitan.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-saitan-float:
    main:                try-saitan-float.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-texel-buffer:
    main:                try-texel-buffer.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-vulkan-guide:
    main:                try-vulkan-guide.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-wavefront-obj:
    main:                try-wavefront-obj.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-image-buffer:
    main:                try-image-buffer.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-no-dynamic-dsc-sets:
    main:                try-no-dynamic-dsc-sets.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
  try-dynamic-dsc-sets:
    main:                try-dynamic-dsc-sets.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd

tests:
  try-my-vulkan-snd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan-snd
