-- This file is automatically generated by the tools/makeEnum.hs
--	% stack runghc --cwd tools/ makeEnum

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Vulkan.Subpass.Enum where

import Foreign.Storable
import Foreign.C.Enum
import Data.Bits
import Data.Word

#include <vulkan/vulkan.h>

enum "DescriptionFlagBits" ''#{type VkSubpassDescriptionFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("DescriptionFlagsZero", 0),
	("DescriptionPerViewAttributesBitNvx",
		#{const VK_SUBPASS_DESCRIPTION_PER_VIEW_ATTRIBUTES_BIT_NVX}),
	("DescriptionPerViewPositionXOnlyBitNvx",
		#{const VK_SUBPASS_DESCRIPTION_PER_VIEW_POSITION_X_ONLY_BIT_NVX}),
	("DescriptionFragmentRegionBitQcom",
		#{const VK_SUBPASS_DESCRIPTION_FRAGMENT_REGION_BIT_QCOM}),
	("DescriptionShaderResolveBitQcom",
		#{const VK_SUBPASS_DESCRIPTION_SHADER_RESOLVE_BIT_QCOM}),
	("DescriptionFlagBitsMaxEnum",
		#{const VK_SUBPASS_DESCRIPTION_FLAG_BITS_MAX_ENUM}) ]

type DescriptionFlags = DescriptionFlagBits
