name:                try-vulkan-core-ext-debug-utils
version:             0.1.0.0
github:              "githubuser/try-vulkan-core-ext-debug-utils"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-vulkan-core-ext-debug-utils#readme>

dependencies:
- base >= 4.7 && < 5
- c-struct
- gpu-vulkan-core

library:
  source-dirs: src

executables:
  try-vulkan-core-ext-debug-utils-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-core-ext-debug-utils

tests:
  try-vulkan-core-ext-debug-utils-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-core-ext-debug-utils
