name:                try-hpack-data-dir
version:             0.1.0.0
github:              "githubuser/try-hpack-data-dir"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-hpack-data-dir#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  try-hpack-data-dir-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-hpack-data-dir

tests:
  try-hpack-data-dir-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-hpack-data-dir

data-dir: foo
data-files:
- bar.txt
