{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE LambdaCase #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Main where

import Data.List
import Data.Char
import Text.Nowdoc

main :: IO ()
main = do
	src <- readFile "/usr/include/vulkan/vulkan_core.h"
	writeFile "src/Vulkan/Format.hsc" $ foo ++ intercalate ",\n" (map makeItem . takeVkFormat $ lines src) ++ " ]\n"

takeVkFormat :: [String] -> [String]
takeVkFormat = map (head . words) . takeWhile (not . (== "} VkFormat;")) . tail
	. dropWhile (not . ("typedef enum VkFormat {" `isPrefixOf`))

makeItem :: String -> String
makeItem cnst = '\t' : nm ++ sp ++ cst
	where
	nm = "(\"" ++ concat (map capitalize . tail $ sep '_' cnst) ++ "\","
	cst = "#{const " ++ cnst ++ "})"
	sp = if 8 + length nm + 1 + length cst + 1 > 80 then "\n\t\t" else " "

sep :: Eq a => a -> [a] -> [[a]]
sep s xs = case d of [] -> [t]; _ : r -> t : sep s r
	where (t, d) = span (/= s) xs
	
capitalize :: String -> String
capitalize = \case
	"" -> ""
	c : cs -> toUpper c : map toLower cs

foo :: String
foo = [nowdoc|
-- This file is automatically generated by the tools/makeEnumVkFormat.hs

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Vulkan.Format where

import Foreign.Storable
import Foreign.C.Enum
import Data.Word

#include <vulkan/vulkan.h>

enum "Format" ''#{type VkFormat} [''Show, ''Eq, ''Storable] [
|]


{-
	("FormatUndefined", #{const VK_FORMAT_UNDEFINED}),
	("FormatR4g4UnormPack8", #{const VK_FORMAT_R4G4_UNORM_PACK8}),
	("FormatR4g4b4a4UnormPack16", #{const VK_FORMAT_R4G4B4A4_UNORM_PACK16}),
	("FormatB4g4r4a4UnormPack16", #{const VK_FORMAT_B4G4R4A4_UNORM_PACK16}),
	-- VK_FORMAT_R5G6B5_UNORM_PACK16
	-- VK_FORMAT_B5G6R5_UNORM_PACK16
	-- VK_FORMAT_R5G5B5A1_UNORM_PACK16
	-- VK_FORMAT_B5G5R5A1_UNORM_PACK16
	-- VK_FORMAT_A1R5G5B5_UNORM_PACK16
	-- ...
	-- VK_FORMAT_R8G8B8A8_SSCALED
	-- VK_FORMAT_R8G8B8A8_UINT
	-- VK_FORMAT_R8G8B8A8_SINT
	-- VK_FORMAT_R8G8B8A8_SRGB
	("FormatB8g8r8a8Unorm", #{const VK_FORMAT_B8G8R8A8_UNORM}),
	-- VK_FORMAT_B8G8R8A8_SNORM
	-- ...
	-- VK_FORMAT_B8G8R8A8_SINT
	("FormatB8g8r8a8Srgb", #{const VK_FORMAT_B8G8R8A8_SRGB}),
	-- VK_FORMAT_A8B8G8R8_UNORM_PACK32
	-- ...
	-- VK_FORMAT_G16_B16R16_2PLANE_422_UNORM_KHR
	("FormatG16B16R163Plane444Unorm",
		#{const VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM})
-}
