name:                try-simple-cairo
version:             0.1.0.0
github:              "githubuser/try-simple-cairo"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-simple-cairo#readme>

dependencies:
- base >= 4.7 && < 5
- text
- simple-cairo
- cairo-image
- JuicyCairo
- JuicyPixels

library:
  source-dirs: src

executables:
  try-simple-cairo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-svg:
    main:                try-svg.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-svg-stream:
    main:                try-svg-stream.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-set-source:
    main:                try-cairo-set-source.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-set-source-surface:
    main:                try-cairo-set-source-surface.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-stroke:
    main:                try-cairo-stroke.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-stroke-preserve:
    main:                try-cairo-stroke-preserve.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo

tests:
  try-simple-cairo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
