name:                try-simple-cairo
version:             0.1.0.0
github:              "githubuser/try-simple-cairo"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-simple-cairo#readme>

dependencies:
- base >= 4.7 && < 5
- primitive
- bytestring
- text
- simple-cairo
- cairo-image
- JuicyCairo
- JuicyPixels
- union-color

library:
  source-dirs: src

executables:
  try-simple-cairo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-svg:
    main:                try-svg.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-svg-stream:
    main:                try-svg-stream.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-set-source:
    main:                try-cairo-set-source.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-set-source-surface:
    main:                try-cairo-set-source-surface.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-stroke:
    main:                try-cairo-stroke.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-stroke-preserve:
    main:                try-cairo-stroke-preserve.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-mask:
    main:                try-cairo-mask.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-mask-surface:
    main:                try-cairo-mask-surface.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-save-restore:
    main:                try-cairo-save-restore.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-clip:
    main:                try-cairo-clip.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-fill-rule:
    main:                try-cairo-fill-rule.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-line-cap:
    main:                try-cairo-line-cap.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-line-join:
    main:                try-cairo-line-join.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-miter-limit:
    main:                try-cairo-miter-limit.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-operator:
    main:                try-cairo-operator.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-new-path:
    main:                try-cairo-new-path.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-new-sub-path:
    main:                try-cairo-new-sub-path.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-curve-to:
    main:                try-cairo-curve-to.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-close-path:
    main:                try-cairo-close-path.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-arc:
    main:                try-cairo-arc.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-path-extents:
    main:                try-cairo-path-extents.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-rel-move-error:
    main:                try-cairo-rel-move-error.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-relative:
    main:                try-cairo-relative.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-pattern-create-rgb:
    main:                try-cairo-pattern-create-rgb.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-pattern-create-radial:
    main:                try-cairo-pattern-create-radial.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-pattern-create-surface:
    main:                try-cairo-pattern-create-surface.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-cairo-pattern-set-matrix:
    main:                try-cairo-pattern-set-matrix.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-pdf:
    main:                try-pdf.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
  try-pdf-stream:
    main:                try-pdf-stream.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo


tests:
  try-simple-cairo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo
