name:                try-bindings-portaudio
version:             0.1.0.0
github:              "YoshikuniJujo/try-bindings-portaudio"
license:             BSD-3-Clause
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "(c) 2025 Yoshikuni Jujo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/try-bindings-portaudio#readme>

dependencies:
- base >= 4.7 && < 5
- stm
- containers
- vector
- bytestring
- linear
- GLFW-b
- bindings-portaudio
- optparse-applicative
- c-enum

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  try-bindings-portaudio-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-bindings-portaudio
  bak:
    main:                main_bak.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-bindings-portaudio
  piano_bak:
    main:                piano_bak.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-bindings-portaudio
  keyevent:
    main:                keyevent.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-bindings-portaudio
  singleNote:
    main:                singleNote.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-bindings-portaudio
  piano:
    main:                piano.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-bindings-portaudio
  keyLogToWave:
    main:                keyLogToWave.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-bindings-portaudio

tests:
  try-bindings-portaudio-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-bindings-portaudio
