name:                try-my-vulkan
version:             0.1.0.0
github:              "githubuser/try-my-vulkan"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-my-vulkan#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- bytestring
- containers
- monads-tf
- GLFW-b
- c-enum
- c-struct
- exception-hierarchy
- ranged-list
- nowdoc
- size-alignment-list

library:
  source-dirs: src
  pkg-config-dependencies:
  - vulkan
  - cglm

executables:
  try-my-vulkan-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan
  try-glm:
    main:                try-glm.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan
  try-draw-triangle:
    main:                try-draw-triangle.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan
  try-allocation:
    main:                try-allocation.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan

tests:
  try-my-vulkan-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-my-vulkan
