name:                hashmap-circuit
version:             0.1.0.0
github:              "githubuser/hashmap-circuit"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hashmap-circuit#readme>

dependencies:
- base >= 4.7 && < 5
- monads-tf
- containers
- hashable
- unordered-containers

library:
  source-dirs: src
  ghc-options:
  - -O2

executables:
  hashmap-circuit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hashmap-circuit
  subtractMap:
    main:                subtractMap.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hashmap-circuit
  subtractHashMap:
    main:                subtractMap.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hashmap-circuit

tests:
  hashmap-circuit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hashmap-circuit
