name:                try-cairo-pdf
version:             0.1.0.0
github:              "githubuser/try-cairo-pdf"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-cairo-pdf#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- directory
- primitive
- bytestring
- simple-cairo

library:
  source-dirs: src

executables:
  try-cairo-pdf-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-cairo-pdf
  try-pdf-bak:
    main:                try-pdf-bak.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-cairo-pdf
  try-pdf:
    main:                try-pdf.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-cairo-pdf
  try-pdf-stream:
    main:                try-pdf-stream.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-cairo-pdf
  try-link-file:
    main:                try-link-file.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-cairo-pdf
  try-cairo-pdf-surface-set-size:
    main:                try-cairo-pdf-surface-set-size.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-cairo-pdf
  try-cairo-pdf-surface-set-thumbnail-size:
    main:                try-cairo-pdf-surface-set-thumbnail-size.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-cairo-pdf

tests:
  try-cairo-pdf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-cairo-pdf
