-- This file is automatically generated by the tools/makeEnum.hs
--	% stack runghc --cwd tools/ makeEnum

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeSynonymInstances #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Vulkan.Ext.DebugUtils.Message.Enum where

import Foreign.Storable
import Foreign.C.Enum
import Data.Bits
import Data.Word

#include <vulkan/vulkan.h>

enum "SeverityFlagBits" ''#{type VkDebugUtilsMessageSeverityFlagBitsEXT}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("SeverityVerboseBit",
		#{const VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT}),
	("SeverityInfoBit",
		#{const VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT}),
	("SeverityWarningBit",
		#{const VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT}),
	("SeverityErrorBit",
		#{const VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT}),
	("SeverityFlagBitsMaxEnum",
		#{const VK_DEBUG_UTILS_MESSAGE_SEVERITY_FLAG_BITS_MAX_ENUM_EXT}) ]

enum "TypeFlagBits" ''#{type VkDebugUtilsMessageTypeFlagBitsEXT}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("TypeGeneralBit",
		#{const VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT}),
	("TypeValidationBit",
		#{const VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT}),
	("TypePerformanceBit",
		#{const VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT}),
	("TypeFlagBitsMaxEnum",
		#{const VK_DEBUG_UTILS_MESSAGE_TYPE_FLAG_BITS_MAX_ENUM_EXT}) ]

type SeverityFlags = SeverityFlagBits
type TypeFlags = TypeFlagBits
