name:                try-moffy-core
version:             0.1.0.5
github:              "YoshikuniJujo/try-moffy-core"
license:             BSD-3-Clause
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "Copyright (c) 2023 Yoshikuni Jujo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            FRP

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/try-moffy-core#readme>

dependencies:
- base >= 4.7 && < 5
- time
- try-type-set
- try-freer-par-monad
- extra-data-yj
- type-flip

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Control.Moffy
    - Control.Moffy.NoThreadId
    - Control.Moffy.Internal.React
    - Control.Moffy.Internal.React.Type
    - Control.Moffy.Internal.Sig
    - Control.Moffy.Internal.Sig.Type
    - Control.Moffy.Event.Lock
    - Control.Moffy.Event.ThreadId
    - Control.Moffy.Event.Time
    - Control.Moffy.Handle
    - Control.Moffy.Handle.Lock
    - Control.Moffy.Handle.ThreadId
    - Control.Moffy.Handle.Time
    - Control.Moffy.Run

tests:
  try-moffy-core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy-core
