-- This file is automatically generated by the tools/makeEnumVkDescriptorSetLayoutCreateFlagBits
--	% stack runghc --cwd tools/ makeEnumVkDescriptorSetLayoutCreateFlagBits

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Vulkan.DescriptorSetLayoutCreateFlagBits where

import Foreign.Storable
import Foreign.C.Enum
import Data.Word
import Data.Bits

#include <vulkan/vulkan.h>

enum "DescriptorSetLayoutCreateFlagBits" ''#{type VkDescriptorSetLayoutCreateFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("DescriptorSetLayoutCreateUpdateAfterBindPoolBit",
		#{const VK_DESCRIPTOR_SET_LAYOUT_CREATE_UPDATE_AFTER_BIND_POOL_BIT}),
	("DescriptorSetLayoutCreatePushDescriptorBitKhr",
		#{const VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR}),
	("DescriptorSetLayoutCreateHostOnlyPoolBitValve",
		#{const VK_DESCRIPTOR_SET_LAYOUT_CREATE_HOST_ONLY_POOL_BIT_VALVE}),
	("DescriptorSetLayoutCreateUpdateAfterBindPoolBitExt",
		#{const VK_DESCRIPTOR_SET_LAYOUT_CREATE_UPDATE_AFTER_BIND_POOL_BIT_EXT}),
	("DescriptorSetLayoutCreateFlagBitsMaxEnum",
		#{const VK_DESCRIPTOR_SET_LAYOUT_CREATE_FLAG_BITS_MAX_ENUM}) ]

type DescriptorSetLayoutCreateFlags = DescriptorSetLayoutCreateFlagBits
