-- This file is automatically generated by the tools/makeEnumVkSamplerAddressMode
--	% stack runghc --cwd tools/ makeEnumVkSamplerAddressMode

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Vulkan.SamplerAddressMode where

import Foreign.Storable
import Foreign.C.Enum
import Data.Word

#include <vulkan/vulkan.h>

enum "SamplerAddressMode" ''#{type VkSamplerAddressMode}
		[''Show, ''Eq, ''Storable] [
	("SamplerAddressModeRepeat", #{const VK_SAMPLER_ADDRESS_MODE_REPEAT}),
	("SamplerAddressModeMirroredRepeat",
		#{const VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT}),
	("SamplerAddressModeClampToEdge",
		#{const VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE}),
	("SamplerAddressModeClampToBorder",
		#{const VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER}),
	("SamplerAddressModeMirrorClampToEdge",
		#{const VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE}),
	("SamplerAddressModeMirrorClampToEdgeKhr",
		#{const VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE_KHR}),
	("SamplerAddressModeMaxEnum",
		#{const VK_SAMPLER_ADDRESS_MODE_MAX_ENUM}) ]
