-- This file is automatically generated by the tools/makeEnumVkCullModeFlagBits
--	% stack runghc --cwd tools/ makeEnumVkCullModeFlagBits

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Vulkan.CullModeFlagBits where

import Foreign.Storable
import Foreign.C.Enum
import Data.Word

#include <vulkan/vulkan.h>

enum "CullModeFlagBits" ''#{type VkCullModeFlagBits} [''Show, ''Eq, ''Storable] [
	("CullModeNone", #{const VK_CULL_MODE_NONE}),
	("CullModeFrontBit", #{const VK_CULL_MODE_FRONT_BIT}),
	("CullModeBackBit", #{const VK_CULL_MODE_BACK_BIT}),
	("CullModeFrontAndBack", #{const VK_CULL_MODE_FRONT_AND_BACK}),
	("CullModeFlagBitsMaxEnum", #{const VK_CULL_MODE_FLAG_BITS_MAX_ENUM}) ]

type CullModeFlags = CullModeFlagBits
