-- This file is automatically generated by the tools/makeEnumVkDescriptorType
--	% stack runghc --cwd tools/ makeEnumVkDescriptorType

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Vulkan.DescriptorType where

import Foreign.Storable
import Foreign.C.Enum
import Data.Word

#include <vulkan/vulkan.h>

enum "DescriptorType" ''#{type VkDescriptorType}
		[''Show, ''Eq, ''Storable] [
	("DescriptorTypeSampler", #{const VK_DESCRIPTOR_TYPE_SAMPLER}),
	("DescriptorTypeCombinedImageSampler",
		#{const VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER}),
	("DescriptorTypeSampledImage",
		#{const VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE}),
	("DescriptorTypeStorageImage",
		#{const VK_DESCRIPTOR_TYPE_STORAGE_IMAGE}),
	("DescriptorTypeUniformTexelBuffer",
		#{const VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER}),
	("DescriptorTypeStorageTexelBuffer",
		#{const VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER}),
	("DescriptorTypeUniformBuffer",
		#{const VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER}),
	("DescriptorTypeStorageBuffer",
		#{const VK_DESCRIPTOR_TYPE_STORAGE_BUFFER}),
	("DescriptorTypeUniformBufferDynamic",
		#{const VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC}),
	("DescriptorTypeStorageBufferDynamic",
		#{const VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC}),
	("DescriptorTypeInputAttachment",
		#{const VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT}),
	("DescriptorTypeInlineUniformBlockExt",
		#{const VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK_EXT}),
	("DescriptorTypeAccelerationStructureKhr",
		#{const VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR}),
	("DescriptorTypeAccelerationStructureNv",
		#{const VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV}),
	("DescriptorTypeMutableValve",
		#{const VK_DESCRIPTOR_TYPE_MUTABLE_VALVE}),
	("DescriptorTypeMaxEnum", #{const VK_DESCRIPTOR_TYPE_MAX_ENUM}) ]
