-- This file is automatically generated by the tools/makeEnumVkDynamicState
--	% stack runghc --cwd tools/ makeEnumVkDynamicState

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Vulkan.DynamicState where

import Foreign.Storable
import Foreign.C.Enum
import Data.Word
import Foreign.Ptr

#include <vulkan/vulkan.h>

enum "DynamicState" ''#{type VkDynamicState}
		[''Show, ''Eq, ''Storable] [
	("DynamicStateViewport", #{const VK_DYNAMIC_STATE_VIEWPORT}),
	("DynamicStateScissor", #{const VK_DYNAMIC_STATE_SCISSOR}),
	("DynamicStateLineWidth", #{const VK_DYNAMIC_STATE_LINE_WIDTH}),
	("DynamicStateDepthBias", #{const VK_DYNAMIC_STATE_DEPTH_BIAS}),
	("DynamicStateBlendConstants",
		#{const VK_DYNAMIC_STATE_BLEND_CONSTANTS}),
	("DynamicStateDepthBounds", #{const VK_DYNAMIC_STATE_DEPTH_BOUNDS}),
	("DynamicStateStencilCompareMask",
		#{const VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK}),
	("DynamicStateStencilWriteMask",
		#{const VK_DYNAMIC_STATE_STENCIL_WRITE_MASK}),
	("DynamicStateStencilReference",
		#{const VK_DYNAMIC_STATE_STENCIL_REFERENCE}),
	("DynamicStateViewportWScalingNv",
		#{const VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_NV}),
	("DynamicStateDiscardRectangleExt",
		#{const VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT}),
	("DynamicStateSampleLocationsExt",
		#{const VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_EXT}),
	("DynamicStateRayTracingPipelineStackSizeKhr",
		#{const VK_DYNAMIC_STATE_RAY_TRACING_PIPELINE_STACK_SIZE_KHR}),
	("DynamicStateViewportShadingRatePaletteNv",
		#{const VK_DYNAMIC_STATE_VIEWPORT_SHADING_RATE_PALETTE_NV}),
	("DynamicStateViewportCoarseSampleOrderNv",
		#{const VK_DYNAMIC_STATE_VIEWPORT_COARSE_SAMPLE_ORDER_NV}),
	("DynamicStateExclusiveScissorNv",
		#{const VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_NV}),
	("DynamicStateFragmentShadingRateKhr",
		#{const VK_DYNAMIC_STATE_FRAGMENT_SHADING_RATE_KHR}),
	("DynamicStateLineStippleExt",
		#{const VK_DYNAMIC_STATE_LINE_STIPPLE_EXT}),
	("DynamicStateCullModeExt", #{const VK_DYNAMIC_STATE_CULL_MODE_EXT}),
	("DynamicStateFrontFaceExt", #{const VK_DYNAMIC_STATE_FRONT_FACE_EXT}),
	("DynamicStatePrimitiveTopologyExt",
		#{const VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY_EXT}),
	("DynamicStateViewportWithCountExt",
		#{const VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT_EXT}),
	("DynamicStateScissorWithCountExt",
		#{const VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT_EXT}),
	("DynamicStateVertexInputBindingStrideExt",
		#{const VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE_EXT}),
	("DynamicStateDepthTestEnableExt",
		#{const VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE_EXT}),
	("DynamicStateDepthWriteEnableExt",
		#{const VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE_EXT}),
	("DynamicStateDepthCompareOpExt",
		#{const VK_DYNAMIC_STATE_DEPTH_COMPARE_OP_EXT}),
	("DynamicStateDepthBoundsTestEnableExt",
		#{const VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE_EXT}),
	("DynamicStateStencilTestEnableExt",
		#{const VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE_EXT}),
	("DynamicStateStencilOpExt", #{const VK_DYNAMIC_STATE_STENCIL_OP_EXT}),
	("DynamicStateVertexInputExt",
		#{const VK_DYNAMIC_STATE_VERTEX_INPUT_EXT}),
	("DynamicStatePatchControlPointsExt",
		#{const VK_DYNAMIC_STATE_PATCH_CONTROL_POINTS_EXT}),
	("DynamicStateRasterizerDiscardEnableExt",
		#{const VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE_EXT}),
	("DynamicStateDepthBiasEnableExt",
		#{const VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE_EXT}),
	("DynamicStateLogicOpExt", #{const VK_DYNAMIC_STATE_LOGIC_OP_EXT}),
	("DynamicStatePrimitiveRestartEnableExt",
		#{const VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE_EXT}),
	("DynamicStateColorWriteEnableExt",
		#{const VK_DYNAMIC_STATE_COLOR_WRITE_ENABLE_EXT}),
	("DynamicStateMaxEnum", #{const VK_DYNAMIC_STATE_MAX_ENUM}) ]

type PtrDynamicState = Ptr DynamicState
