-- This file is automatically generated by the tools/makeEnumVkPipelineCreateFlagBits
--	% stack runghc --cwd tools/ makeEnumVkPipelineCreateFlagBits

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Vulkan.PipelineCreateFlagBits where

import Foreign.Storable
import Foreign.C.Enum
import Data.Word
import Data.Bits

#include <vulkan/vulkan.h>

enum "PipelineCreateFlagBits" ''#{type VkPipelineCreateFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("PipelineCreateFlagsZero", 0),
	("PipelineCreateDisableOptimizationBit",
		#{const VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT}),
	("PipelineCreateAllowDerivativesBit",
		#{const VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT}),
	("PipelineCreateDerivativeBit",
		#{const VK_PIPELINE_CREATE_DERIVATIVE_BIT}),
	("PipelineCreateViewIndexFromDeviceIndexBit",
		#{const VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT}),
	("PipelineCreateDispatchBaseBit",
		#{const VK_PIPELINE_CREATE_DISPATCH_BASE_BIT}),
	("PipelineRasterizationStateCreateFragmentShadingRateAttachmentBitKhr",
		#{const VK_PIPELINE_RASTERIZATION_STATE_CREATE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR}),
	("PipelineRasterizationStateCreateFragmentDensityMapAttachmentBitExt",
		#{const VK_PIPELINE_RASTERIZATION_STATE_CREATE_FRAGMENT_DENSITY_MAP_ATTACHMENT_BIT_EXT}),
	("PipelineCreateRayTracingNoNullAnyHitShadersBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_ANY_HIT_SHADERS_BIT_KHR}),
	("PipelineCreateRayTracingNoNullClosestHitShadersBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_CLOSEST_HIT_SHADERS_BIT_KHR}),
	("PipelineCreateRayTracingNoNullMissShadersBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_MISS_SHADERS_BIT_KHR}),
	("PipelineCreateRayTracingNoNullIntersectionShadersBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_INTERSECTION_SHADERS_BIT_KHR}),
	("PipelineCreateRayTracingSkipTrianglesBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_SKIP_TRIANGLES_BIT_KHR}),
	("PipelineCreateRayTracingSkipAabbsBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_SKIP_AABBS_BIT_KHR}),
	("PipelineCreateRayTracingShaderGroupHandleCaptureReplayBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_SHADER_GROUP_HANDLE_CAPTURE_REPLAY_BIT_KHR}),
	("PipelineCreateDeferCompileBitNv",
		#{const VK_PIPELINE_CREATE_DEFER_COMPILE_BIT_NV}),
	("PipelineCreateCaptureStatisticsBitKhr",
		#{const VK_PIPELINE_CREATE_CAPTURE_STATISTICS_BIT_KHR}),
	("PipelineCreateCaptureInternalRepresentationsBitKhr",
		#{const VK_PIPELINE_CREATE_CAPTURE_INTERNAL_REPRESENTATIONS_BIT_KHR}),
	("PipelineCreateIndirectBindableBitNv",
		#{const VK_PIPELINE_CREATE_INDIRECT_BINDABLE_BIT_NV}),
	("PipelineCreateLibraryBitKhr",
		#{const VK_PIPELINE_CREATE_LIBRARY_BIT_KHR}),
	("PipelineCreateFailOnPipelineCompileRequiredBitExt",
		#{const VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT_EXT}),
	("PipelineCreateEarlyReturnOnFailureBitExt",
		#{const VK_PIPELINE_CREATE_EARLY_RETURN_ON_FAILURE_BIT_EXT}),
	("PipelineCreateRayTracingAllowMotionBitNv",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_ALLOW_MOTION_BIT_NV}),
	("PipelineCreateDispatchBase",
		#{const VK_PIPELINE_CREATE_DISPATCH_BASE}),
	("PipelineCreateViewIndexFromDeviceIndexBitKhr",
		#{const VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT_KHR}),
	("PipelineCreateDispatchBaseKhr",
		#{const VK_PIPELINE_CREATE_DISPATCH_BASE_KHR}),
	("PipelineCreateFlagBitsMaxEnum",
		#{const VK_PIPELINE_CREATE_FLAG_BITS_MAX_ENUM}) ]

type PipelineCreateFlags = PipelineCreateFlagBits
