-- This file is automatically generated by the tools/makeEnumVkPipelineStageFlagBits.hs
--	% stack runghc --cwd tools/ makeEnumVkPipelineStageFlagBits

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Vulkan.PipelineStageFlagBits where

import Foreign.Storable
import Foreign.C.Enum
import Data.Word
import Data.Bits
import Foreign.Ptr

#include <vulkan/vulkan.h>

enum "PipelineStageFlagBits" ''#{type VkPipelineStageFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("PipelineStageFlagsZero", 0),
	("PipelineStageTopOfPipeBit",
		#{const VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT}),
	("PipelineStageDrawIndirectBit",
		#{const VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT}),
	("PipelineStageVertexInputBit",
		#{const VK_PIPELINE_STAGE_VERTEX_INPUT_BIT}),
	("PipelineStageVertexShaderBit",
		#{const VK_PIPELINE_STAGE_VERTEX_SHADER_BIT}),
	("PipelineStageTessellationControlShaderBit",
		#{const VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT}),
	("PipelineStageTessellationEvaluationShaderBit",
		#{const VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT}),
	("PipelineStageGeometryShaderBit",
		#{const VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT}),
	("PipelineStageFragmentShaderBit",
		#{const VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT}),
	("PipelineStageEarlyFragmentTestsBit",
		#{const VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT}),
	("PipelineStageLateFragmentTestsBit",
		#{const VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT}),
	("PipelineStageColorAttachmentOutputBit",
		#{const VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT}),
	("PipelineStageComputeShaderBit",
		#{const VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT}),
	("PipelineStageTransferBit", #{const VK_PIPELINE_STAGE_TRANSFER_BIT}),
	("PipelineStageBottomOfPipeBit",
		#{const VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT}),
	("PipelineStageHostBit", #{const VK_PIPELINE_STAGE_HOST_BIT}),
	("PipelineStageAllGraphicsBit",
		#{const VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT}),
	("PipelineStageAllCommandsBit",
		#{const VK_PIPELINE_STAGE_ALL_COMMANDS_BIT}),
	("PipelineStageTransformFeedbackBitExt",
		#{const VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT}),
	("PipelineStageConditionalRenderingBitExt",
		#{const VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT}),
	("PipelineStageAccelerationStructureBuildBitKhr",
		#{const VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR}),
	("PipelineStageRayTracingShaderBitKhr",
		#{const VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR}),
	("PipelineStageTaskShaderBitNv",
		#{const VK_PIPELINE_STAGE_TASK_SHADER_BIT_NV}),
	("PipelineStageMeshShaderBitNv",
		#{const VK_PIPELINE_STAGE_MESH_SHADER_BIT_NV}),
	("PipelineStageFragmentDensityProcessBitExt",
		#{const VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT}),
	("PipelineStageFragmentShadingRateAttachmentBitKhr",
		#{const VK_PIPELINE_STAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR}),
	("PipelineStageCommandPreprocessBitNv",
		#{const VK_PIPELINE_STAGE_COMMAND_PREPROCESS_BIT_NV}),
	("PipelineStageNoneKhr", #{const VK_PIPELINE_STAGE_NONE_KHR}),
	("PipelineStageShadingRateImageBitNv",
		#{const VK_PIPELINE_STAGE_SHADING_RATE_IMAGE_BIT_NV}),
	("PipelineStageRayTracingShaderBitNv",
		#{const VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_NV}),
	("PipelineStageAccelerationStructureBuildBitNv",
		#{const VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_NV}),
	("PipelineStageFlagBitsMaxEnum",
		#{const VK_PIPELINE_STAGE_FLAG_BITS_MAX_ENUM}) ]

type PipelineStageFlags = PipelineStageFlagBits
type PtrPipelineStageFlags = Ptr PipelineStageFlags
