-- This file is automatically generated by the tools/makeEnumVkQueryPipelineStatisticFlagBits.hs
--	% stack runghc --cwd tools/ makeEnumVkQueryPipelineStatisticFlagBits

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Vulkan.QueryPipelineStatisticFlagBits where

import Foreign.Storable
import Foreign.C.Enum
import Data.Word
import Data.Bits

#include <vulkan/vulkan.h>

enum "QueryPipelineStatisticFlagBits" ''#{type VkQueryPipelineStatisticFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("QueryPipelineStatisticFlagsZero", 0),
	("QueryPipelineStatisticInputAssemblyVerticesBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT}),
	("QueryPipelineStatisticInputAssemblyPrimitivesBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT}),
	("QueryPipelineStatisticVertexShaderInvocationsBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT}),
	("QueryPipelineStatisticGeometryShaderInvocationsBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT}),
	("QueryPipelineStatisticGeometryShaderPrimitivesBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT}),
	("QueryPipelineStatisticClippingInvocationsBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT}),
	("QueryPipelineStatisticClippingPrimitivesBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT}),
	("QueryPipelineStatisticFragmentShaderInvocationsBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT}),
	("QueryPipelineStatisticTessellationControlShaderPatchesBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT}),
	("QueryPipelineStatisticTessellationEvaluationShaderInvocationsBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT}),
	("QueryPipelineStatisticComputeShaderInvocationsBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT}),
	("QueryPipelineStatisticFlagBitsMaxEnum",
		#{const VK_QUERY_PIPELINE_STATISTIC_FLAG_BITS_MAX_ENUM}) ]

type QueryPipelineStatisticFlags = QueryPipelineStatisticFlagBits
