-- This file is automatically generated by the tools/makeEnumVkSubpassDescriptionFlagBits
--	% stack runghc --cwd tools/ makeEnumVkSubpassDescriptionFlagBits

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Vulkan.SubpassDescriptionFlagBits where

import Foreign.Storable
import Foreign.C.Enum
import Data.Word
import Data.Bits

#include <vulkan/vulkan.h>

enum "SubpassDescriptionFlagBits" ''#{type VkSubpassDescriptionFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("SubpassDescriptionFlagsZero", 0),
	("SubpassDescriptionPerViewAttributesBitNvx",
		#{const VK_SUBPASS_DESCRIPTION_PER_VIEW_ATTRIBUTES_BIT_NVX}),
	("SubpassDescriptionPerViewPositionXOnlyBitNvx",
		#{const VK_SUBPASS_DESCRIPTION_PER_VIEW_POSITION_X_ONLY_BIT_NVX}),
	("SubpassDescriptionFragmentRegionBitQcom",
		#{const VK_SUBPASS_DESCRIPTION_FRAGMENT_REGION_BIT_QCOM}),
	("SubpassDescriptionShaderResolveBitQcom",
		#{const VK_SUBPASS_DESCRIPTION_SHADER_RESOLVE_BIT_QCOM}),
	("SubpassDescriptionFlagBitsMaxEnum",
		#{const VK_SUBPASS_DESCRIPTION_FLAG_BITS_MAX_ENUM}) ]

type SubpassDescriptionFlags = SubpassDescriptionFlagBits
