name:                try-maybe-type-values
version:             0.1.0.0
github:              "githubuser/try-maybe-type-values"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-maybe-type-values#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- monads-tf
- time
- random
- simple-field
- type-flip
- extra-data-yj
- http-conduit
- bytestring
- aeson

library:
  source-dirs: src

executables:
  try-maybe-type-values-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-maybe-type-values

tests:
  try-maybe-type-values-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-maybe-type-values
