-- This file is automatically generated by the tools/makeEnum.hs
--	% stack runghc --cwd tools/ makeEnum

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Vulkan.Pipeline.Enum where

import Foreign.Storable
import Foreign.C.Enum
import Data.Bits
import Data.Word

#include <vulkan/vulkan.h>

enum "BindPoint" ''#{type VkPipelineBindPoint}
		[''Show, ''Storable] [
	("BindPointGraphics", #{const VK_PIPELINE_BIND_POINT_GRAPHICS}),
	("BindPointCompute", #{const VK_PIPELINE_BIND_POINT_COMPUTE}),
	("BindPointRayTracingKhr",
		#{const VK_PIPELINE_BIND_POINT_RAY_TRACING_KHR}),
	("BindPointSubpassShadingHuawei",
		#{const VK_PIPELINE_BIND_POINT_SUBPASS_SHADING_HUAWEI}),
	("BindPointRayTracingNv",
		#{const VK_PIPELINE_BIND_POINT_RAY_TRACING_NV}),
	("BindPointMaxEnum", #{const VK_PIPELINE_BIND_POINT_MAX_ENUM}) ]

enum "StageFlagBits" ''#{type VkPipelineStageFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("StageFlagsZero", 0),
	("StageTopOfPipeBit",
		#{const VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT}),
	("StageDrawIndirectBit",
		#{const VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT}),
	("StageVertexInputBit",
		#{const VK_PIPELINE_STAGE_VERTEX_INPUT_BIT}),
	("StageVertexShaderBit",
		#{const VK_PIPELINE_STAGE_VERTEX_SHADER_BIT}),
	("StageTessellationControlShaderBit",
		#{const VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT}),
	("StageTessellationEvaluationShaderBit",
		#{const VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT}),
	("StageGeometryShaderBit",
		#{const VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT}),
	("StageFragmentShaderBit",
		#{const VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT}),
	("StageEarlyFragmentTestsBit",
		#{const VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT}),
	("StageLateFragmentTestsBit",
		#{const VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT}),
	("StageColorAttachmentOutputBit",
		#{const VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT}),
	("StageComputeShaderBit",
		#{const VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT}),
	("StageTransferBit", #{const VK_PIPELINE_STAGE_TRANSFER_BIT}),
	("StageBottomOfPipeBit",
		#{const VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT}),
	("StageHostBit", #{const VK_PIPELINE_STAGE_HOST_BIT}),
	("StageAllGraphicsBit",
		#{const VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT}),
	("StageAllCommandsBit",
		#{const VK_PIPELINE_STAGE_ALL_COMMANDS_BIT}),
	("StageTransformFeedbackBitExt",
		#{const VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT}),
	("StageConditionalRenderingBitExt",
		#{const VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT}),
	("StageAccelerationStructureBuildBitKhr",
		#{const VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR}),
	("StageRayTracingShaderBitKhr",
		#{const VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR}),
	("StageTaskShaderBitNv",
		#{const VK_PIPELINE_STAGE_TASK_SHADER_BIT_NV}),
	("StageMeshShaderBitNv",
		#{const VK_PIPELINE_STAGE_MESH_SHADER_BIT_NV}),
	("StageFragmentDensityProcessBitExt",
		#{const VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT}),
	("StageFragmentShadingRateAttachmentBitKhr",
		#{const VK_PIPELINE_STAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR}),
	("StageCommandPreprocessBitNv",
		#{const VK_PIPELINE_STAGE_COMMAND_PREPROCESS_BIT_NV}),
	("StageNoneKhr", #{const VK_PIPELINE_STAGE_NONE_KHR}),
	("StageShadingRateImageBitNv",
		#{const VK_PIPELINE_STAGE_SHADING_RATE_IMAGE_BIT_NV}),
	("StageRayTracingShaderBitNv",
		#{const VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_NV}),
	("StageAccelerationStructureBuildBitNv",
		#{const VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_NV}),
	("StageFlagBitsMaxEnum",
		#{const VK_PIPELINE_STAGE_FLAG_BITS_MAX_ENUM}) ]

enum "CreateFlagBits" ''#{type VkPipelineCreateFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("CreateFlagsZero", 0),
	("CreateDisableOptimizationBit",
		#{const VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT}),
	("CreateAllowDerivativesBit",
		#{const VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT}),
	("CreateDerivativeBit",
		#{const VK_PIPELINE_CREATE_DERIVATIVE_BIT}),
	("CreateViewIndexFromDeviceIndexBit",
		#{const VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT}),
	("CreateDispatchBaseBit",
		#{const VK_PIPELINE_CREATE_DISPATCH_BASE_BIT}),
	("RasterizationStateCreateFragmentShadingRateAttachmentBitKhr",
		#{const VK_PIPELINE_RASTERIZATION_STATE_CREATE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR}),
	("RasterizationStateCreateFragmentDensityMapAttachmentBitExt",
		#{const VK_PIPELINE_RASTERIZATION_STATE_CREATE_FRAGMENT_DENSITY_MAP_ATTACHMENT_BIT_EXT}),
	("CreateRayTracingNoNullAnyHitShadersBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_ANY_HIT_SHADERS_BIT_KHR}),
	("CreateRayTracingNoNullClosestHitShadersBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_CLOSEST_HIT_SHADERS_BIT_KHR}),
	("CreateRayTracingNoNullMissShadersBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_MISS_SHADERS_BIT_KHR}),
	("CreateRayTracingNoNullIntersectionShadersBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_INTERSECTION_SHADERS_BIT_KHR}),
	("CreateRayTracingSkipTrianglesBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_SKIP_TRIANGLES_BIT_KHR}),
	("CreateRayTracingSkipAabbsBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_SKIP_AABBS_BIT_KHR}),
	("CreateRayTracingShaderGroupHandleCaptureReplayBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_SHADER_GROUP_HANDLE_CAPTURE_REPLAY_BIT_KHR}),
	("CreateDeferCompileBitNv",
		#{const VK_PIPELINE_CREATE_DEFER_COMPILE_BIT_NV}),
	("CreateCaptureStatisticsBitKhr",
		#{const VK_PIPELINE_CREATE_CAPTURE_STATISTICS_BIT_KHR}),
	("CreateCaptureInternalRepresentationsBitKhr",
		#{const VK_PIPELINE_CREATE_CAPTURE_INTERNAL_REPRESENTATIONS_BIT_KHR}),
	("CreateIndirectBindableBitNv",
		#{const VK_PIPELINE_CREATE_INDIRECT_BINDABLE_BIT_NV}),
	("CreateLibraryBitKhr",
		#{const VK_PIPELINE_CREATE_LIBRARY_BIT_KHR}),
	("CreateFailOnPipelineCompileRequiredBitExt",
		#{const VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT_EXT}),
	("CreateEarlyReturnOnFailureBitExt",
		#{const VK_PIPELINE_CREATE_EARLY_RETURN_ON_FAILURE_BIT_EXT}),
	("CreateRayTracingAllowMotionBitNv",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_ALLOW_MOTION_BIT_NV}),
	("CreateDispatchBase",
		#{const VK_PIPELINE_CREATE_DISPATCH_BASE}),
	("CreateViewIndexFromDeviceIndexBitKhr",
		#{const VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT_KHR}),
	("CreateDispatchBaseKhr",
		#{const VK_PIPELINE_CREATE_DISPATCH_BASE_KHR}),
	("CreateFlagBitsMaxEnum",
		#{const VK_PIPELINE_CREATE_FLAG_BITS_MAX_ENUM}) ]

type StageFlags = StageFlagBits
type CreateFlags = CreateFlagBits
