name:                try-gpu-vulkan-middle-khr-surface-glfw
version:             0.1.0.0
github:              "githubuser/try-gpu-vulkan-middle-khr-surface-glfw"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-gpu-vulkan-middle-khr-surface-glfw#readme>

dependencies:
- base >= 4.7 && < 5
- GLFW-b
- gpu-vulkan-middle
- gpu-vulkan-middle-khr-surface
- typelevel-tools-yj

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  try-gpu-vulkan-middle-khr-surface-glfw-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gpu-vulkan-middle-khr-surface-glfw
