name:                try-use-c-lib
version:             0.1.0.0
github:              "githubuser/try-use-c-lib"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-use-c-lib#readme>

dependencies:
- base >= 4.7 && < 5
- c-enum
- exception-hierarchy

library:
  source-dirs: src
  include-dirs: include
  c-sources: csrc/human.c

executables:
  try-use-c-lib-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-use-c-lib

tests:
  try-use-c-lib-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-use-c-lib
