-- This file is automatically generated by the tools/makeEnum.hs
--	% stack runghc --cwd tools/ makeEnum

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Vulkan.Buffer.Enum where

import Foreign.Storable
import Foreign.C.Enum
import Data.Bits
import Data.Word

#include <vulkan/vulkan.h>

enum "CreateFlagBits" ''#{type VkBufferCreateFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("CreateFlagsZero", 0),
	("CreateSparseBindingBit",
		#{const VK_BUFFER_CREATE_SPARSE_BINDING_BIT}),
	("CreateSparseResidencyBit",
		#{const VK_BUFFER_CREATE_SPARSE_RESIDENCY_BIT}),
	("CreateSparseAliasedBit",
		#{const VK_BUFFER_CREATE_SPARSE_ALIASED_BIT}),
	("CreateProtectedBit", #{const VK_BUFFER_CREATE_PROTECTED_BIT}),
	("CreateDeviceAddressCaptureReplayBit",
		#{const VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT}),
	("CreateDeviceAddressCaptureReplayBitExt",
		#{const VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_EXT}),
	("CreateDeviceAddressCaptureReplayBitKhr",
		#{const VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_KHR}),
	("CreateFlagBitsMaxEnum",
		#{const VK_BUFFER_CREATE_FLAG_BITS_MAX_ENUM}) ]

type CreateFlags = CreateFlagBits
