module Database.SmplstSQLite3.Exception (
	SQLiteException(..),

	SQLITE_ERROR(..),
	SQLITE_INTERNAL(..),
	SQLITE_PERM(..),

	SQLITE_ABORT(..),
	SQLITE_ABORT_PLAIN(..),
	SQLITE_ABORT_ROLLBACK(..),

	SQLITE_BUSY(..),
	SQLITE_BUSY_PLAIN(..),
	SQLITE_BUSY_RECOVERY(..),
	SQLITE_BUSY_SNAPSHOT(..),

	SQLITE_LOCKED(..),
	SQLITE_LOCKED_PLAIN(..),
	SQLITE_LOCKED_SHAREDCACHE(..),

	SQLITE_NOMEM(..),

	SQLITE_READONLY(..),
	SQLITE_READONLY_PLAIN(..),
	SQLITE_READONLY_RECOVERY(..),
	SQLITE_READONLY_CANTLOCK(..),
	SQLITE_READONLY_ROLLBACK(..),
	SQLITE_READONLY_DBMOVED(..),

	SQLITE_INTERRUPT(..),

	SQLITE_IOERR(..),
	SQLITE_IOERR_PLAIN(..),
	SQLITE_IOERR_READ(..),
	SQLITE_IOERR_SHORT_READ(..),
	SQLITE_IOERR_WRITE(..),
	SQLITE_IOERR_FSYNC(..),
	SQLITE_IOERR_DIR_FSYNC(..),
	SQLITE_IOERR_TRUNCATE(..),
	SQLITE_IOERR_FSTAT(..),
	SQLITE_IOERR_UNLOCK(..),
	SQLITE_IOERR_RDLOCK(..),
	SQLITE_IOERR_DELETE(..),
	SQLITE_IOERR_BLOCKED(..),
	SQLITE_IOERR_NOMEM(..),
	SQLITE_IOERR_ACCESS(..),
	SQLITE_IOERR_CHECKRESERVEDLOCK(..),
	SQLITE_IOERR_LOCK(..),
	SQLITE_IOERR_CLOSE(..),
	SQLITE_IOERR_DIR_CLOSE(..),
	SQLITE_IOERR_SHMOPEN(..),
	SQLITE_IOERR_SHMSIZE(..),
	SQLITE_IOERR_SHMLOCK(..),
	SQLITE_IOERR_SHMMAP(..),
	SQLITE_IOERR_SEEK(..),
	SQLITE_IOERR_DELETE_NOENT(..),
	SQLITE_IOERR_MMAP(..),
	SQLITE_IOERR_GETTEMPPATH(..),
	SQLITE_IOERR_CONVPATH(..),

	SQLITE_CORRUPT(..),
	SQLITE_CORRUPT_PLAIN(..),
	SQLITE_CORRUPT_VTAB(..),

	SQLITE_NOTFOUND(..),
	SQLITE_FULL(..),

	SQLITE_CANTOPEN(..),
	SQLITE_CANTOPEN_PLAIN(..),
	SQLITE_CANTOPEN_NOTEMPDIR(..),
	SQLITE_CANTOPEN_ISDIR(..),
	SQLITE_CANTOPEN_FULLPATH(..),
	SQLITE_CANTOPEN_CONVPATH(..),

	SQLITE_PROTOCOL(..),
	SQLITE_EMPTY(..),
	SQLITE_SCHEMA(..),
	SQLITE_TOOBIG(..),

	SQLITE_CONSTRAINT(..),
	SQLITE_CONSTRAINT_PLAIN(..),
	SQLITE_CONSTRAINT_CHECK(..),
	SQLITE_CONSTRAINT_COMMITHOOK(..),
	SQLITE_CONSTRAINT_FOREIGNKEY(..),
	SQLITE_CONSTRAINT_FUNCTION(..),
	SQLITE_CONSTRAINT_NOTNULL(..),
	SQLITE_CONSTRAINT_PRIMARYKEY(..),
	SQLITE_CONSTRAINT_TRIGGER(..),
	SQLITE_CONSTRAINT_UNIQUE(..),
	SQLITE_CONSTRAINT_VTAB(..),
	SQLITE_CONSTRAINT_ROWID(..),

	SQLITE_MISMATCH(..),
	SQLITE_MISUSE(..),
	SQLITE_NOLFS(..),

	SQLITE_AUTH(..),
	SQLITE_AUTH_PLAIN(..),
	SQLITE_AUTH_USER(..),

	SQLITE_FORMAT(..),
	SQLITE_RANGE(..),
	SQLITE_NOTADB(..),

	SQLITE_NOTICE(..),
	SQLITE_NOTICE_PLAIN(..),
	SQLITE_NOTICE_RECOVER_WAL(..),
	SQLITE_NOTICE_RECOVER_ROLLBACK(..),

	SQLITE_WARNING(..),
	SQLITE_WARNING_PLAIN(..),
	SQLITE_WARNING_AUTOINDEX(..),

	SQLITE_BIND_ERROR(..),
	SQLITE_ERROR_OTHER(..),
	) where

import Database.SmplstSQLite3.Exception.Internal
