-- This file is automatically generated by the tools/makeEnum.hs
--	% stack runghc --cwd tools/ makeEnum

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeSynonymInstances #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-missing-export-lists -fno-warn-tabs #-}

module Gpu.Vulkan.Query.Enum where

import Foreign.Storable
import Foreign.C.Enum
import Data.Bits
import Data.Word

#include <vulkan/vulkan.h>

enum "PipelineStatisticFlagBits" ''#{type VkQueryPipelineStatisticFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("PipelineStatisticInputAssemblyVerticesBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT}),
	("PipelineStatisticInputAssemblyPrimitivesBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT}),
	("PipelineStatisticVertexShaderInvocationsBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT}),
	("PipelineStatisticGeometryShaderInvocationsBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT}),
	("PipelineStatisticGeometryShaderPrimitivesBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT}),
	("PipelineStatisticClippingInvocationsBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT}),
	("PipelineStatisticClippingPrimitivesBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT}),
	("PipelineStatisticFragmentShaderInvocationsBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT}),
	("PipelineStatisticTessellationControlShaderPatchesBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT}),
	("PipelineStatisticTessellationEvaluationShaderInvocationsBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT}),
	("PipelineStatisticComputeShaderInvocationsBit",
		#{const VK_QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT}),
	("PipelineStatisticTaskShaderInvocationsBitExt",
		#{const VK_QUERY_PIPELINE_STATISTIC_TASK_SHADER_INVOCATIONS_BIT_EXT}),
	("PipelineStatisticMeshShaderInvocationsBitExt",
		#{const VK_QUERY_PIPELINE_STATISTIC_MESH_SHADER_INVOCATIONS_BIT_EXT}),
	("PipelineStatisticClusterCullingShaderInvocationsBitHuawei",
		#{const VK_QUERY_PIPELINE_STATISTIC_CLUSTER_CULLING_SHADER_INVOCATIONS_BIT_HUAWEI}),
	("PipelineStatisticFlagBitsMaxEnum",
		#{const VK_QUERY_PIPELINE_STATISTIC_FLAG_BITS_MAX_ENUM}) ]

enum "ControlFlagBits" ''#{type VkQueryControlFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("ControlPreciseBit", #{const VK_QUERY_CONTROL_PRECISE_BIT}),
	("ControlFlagBitsMaxEnum",
		#{const VK_QUERY_CONTROL_FLAG_BITS_MAX_ENUM}) ]

enum "ResultFlagBits" ''#{type VkQueryResultFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("Result64Bit", #{const VK_QUERY_RESULT_64_BIT}),
	("ResultWaitBit", #{const VK_QUERY_RESULT_WAIT_BIT}),
	("ResultWithAvailabilityBit",
		#{const VK_QUERY_RESULT_WITH_AVAILABILITY_BIT}),
	("ResultPartialBit", #{const VK_QUERY_RESULT_PARTIAL_BIT}),
	("ResultWithStatusBitKhr",
		#{const VK_QUERY_RESULT_WITH_STATUS_BIT_KHR}),
	("ResultFlagBitsMaxEnum",
		#{const VK_QUERY_RESULT_FLAG_BITS_MAX_ENUM}) ]

enum "Type" ''#{type VkQueryType}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("TypeOcclusion", #{const VK_QUERY_TYPE_OCCLUSION}),
	("TypePipelineStatistics",
		#{const VK_QUERY_TYPE_PIPELINE_STATISTICS}),
	("TypeTimestamp", #{const VK_QUERY_TYPE_TIMESTAMP}),
	("TypeResultStatusOnlyKhr",
		#{const VK_QUERY_TYPE_RESULT_STATUS_ONLY_KHR}),
	("TypeTransformFeedbackStreamExt",
		#{const VK_QUERY_TYPE_TRANSFORM_FEEDBACK_STREAM_EXT}),
	("TypePerformanceQueryKhr",
		#{const VK_QUERY_TYPE_PERFORMANCE_QUERY_KHR}),
	("TypeAccelerationStructureCompactedSizeKhr",
		#{const VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_KHR}),
	("TypeAccelerationStructureSerializationSizeKhr",
		#{const VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_SIZE_KHR}),
	("TypeAccelerationStructureCompactedSizeNv",
		#{const VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_NV}),
	("TypePerformanceQueryIntel",
		#{const VK_QUERY_TYPE_PERFORMANCE_QUERY_INTEL}),
	("TypeMeshPrimitivesGeneratedExt",
		#{const VK_QUERY_TYPE_MESH_PRIMITIVES_GENERATED_EXT}),
	("TypePrimitivesGeneratedExt",
		#{const VK_QUERY_TYPE_PRIMITIVES_GENERATED_EXT}),
	("TypeAccelerationStructureSerializationBottomLevelPointersKhr",
		#{const VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_BOTTOM_LEVEL_POINTERS_KHR}),
	("TypeAccelerationStructureSizeKhr",
		#{const VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SIZE_KHR}),
	("TypeMicromapSerializationSizeExt",
		#{const VK_QUERY_TYPE_MICROMAP_SERIALIZATION_SIZE_EXT}),
	("TypeMicromapCompactedSizeExt",
		#{const VK_QUERY_TYPE_MICROMAP_COMPACTED_SIZE_EXT}),
	("TypeMaxEnum", #{const VK_QUERY_TYPE_MAX_ENUM}) ]

type PipelineStatisticFlags = PipelineStatisticFlagBits
type ControlFlags = ControlFlagBits
type ResultFlags = ResultFlagBits
