-- This file is automatically generated by the tools/makeEnum.hs
--	% stack runghc --cwd tools/ makeEnum

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeSynonymInstances #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-missing-export-lists -fno-warn-tabs #-}

module Gpu.Vulkan.Subpass.Enum where

import Foreign.Storable
import Foreign.C.Enum
import Data.Bits
import Data.Word

#include <vulkan/vulkan.h>

enum "DescriptionFlagBits" ''#{type VkSubpassDescriptionFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("DescriptionFlagsZero", 0),
	("DescriptionPerViewAttributesBitNvx",
		#{const VK_SUBPASS_DESCRIPTION_PER_VIEW_ATTRIBUTES_BIT_NVX}),
	("DescriptionPerViewPositionXOnlyBitNvx",
		#{const VK_SUBPASS_DESCRIPTION_PER_VIEW_POSITION_X_ONLY_BIT_NVX}),
	("DescriptionFragmentRegionBitQcom",
		#{const VK_SUBPASS_DESCRIPTION_FRAGMENT_REGION_BIT_QCOM}),
	("DescriptionShaderResolveBitQcom",
		#{const VK_SUBPASS_DESCRIPTION_SHADER_RESOLVE_BIT_QCOM}),
	("DescriptionRasterizationOrderAttachmentColorAccessBitExt",
		#{const VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_COLOR_ACCESS_BIT_EXT}),
	("DescriptionRasterizationOrderAttachmentDepthAccessBitExt",
		#{const VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_DEPTH_ACCESS_BIT_EXT}),
	("DescriptionRasterizationOrderAttachmentStencilAccessBitExt",
		#{const VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_STENCIL_ACCESS_BIT_EXT}),
	("DescriptionEnableLegacyDitheringBitExt",
		#{const VK_SUBPASS_DESCRIPTION_ENABLE_LEGACY_DITHERING_BIT_EXT}),
	("DescriptionRasterizationOrderAttachmentColorAccessBitArm",
		#{const VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_COLOR_ACCESS_BIT_ARM}),
	("DescriptionRasterizationOrderAttachmentDepthAccessBitArm",
		#{const VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_DEPTH_ACCESS_BIT_ARM}),
	("DescriptionRasterizationOrderAttachmentStencilAccessBitArm",
		#{const VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_STENCIL_ACCESS_BIT_ARM}),
	("DescriptionFlagBitsMaxEnum",
		#{const VK_SUBPASS_DESCRIPTION_FLAG_BITS_MAX_ENUM}) ]

enum "Contents" ''#{type VkSubpassContents}
		[''Show, ''Eq, ''Storable] [
	("ContentsInline", #{const VK_SUBPASS_CONTENTS_INLINE}),
	("ContentsSecondaryCommandBuffers",
		#{const VK_SUBPASS_CONTENTS_SECONDARY_COMMAND_BUFFERS}),
	("ContentsMaxEnum", #{const VK_SUBPASS_CONTENTS_MAX_ENUM}) ]

type DescriptionFlags = DescriptionFlagBits
