name:                try-gdk-gl
version:             0.1.0.0
github:              "githubuser/try-gdk-gl"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-gdk-gl#readme>

dependencies:
- base >= 4.7 && < 5
- simple-gdk3
- simple-cairo
- GLUT
- OpenGL

library:
  source-dirs: src

executables:
  try-gdk-gl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gdk-gl
  try-fbo:
    main:                try-fbo.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gdk-gl

tests:
  try-gdk-gl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gdk-gl
