name:                try-vulkan-compute
version:             0.1.0.0
github:              "githubuser/try-vulkan-compute"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-vulkan-compute#readme>

dependencies:
- base >= 4.7 && < 5
- stm
- bytestring
- text
- parallel
- random
- data-default
- array
- vector
- time
- filepath
- JuicyPixels
- try-gpu-vulkan
- try-gpu-vulkan-khr
- try-gpu-vulkan-ext-debug-utils
- try-shaderc
- try-language-spir-v
- try-hetero-parameter-list
- try-storable-generic
- ranged-list
- typelevel-tools
- temporary

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  c-sources:
  - csrc/hello.c
  - csrc/bitonicSortPairs.c
  - csrc/quicksort.c
  - csrc/bitonic_sort.c
  - csrc/mandelbrot.c

executables:
  try-hello-world:
    main:                try-hello-world.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-push-constant:
    main:                try-push-constant.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-saitan-simple:
    main:                try-saitan-simple.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-bitonic-sort:
    main:                try-bitonic-sort.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-bitonic-sort-new:
    main:                try-bitonic-sort-new.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-bitonic-sort-cpu:
    main:                try-bitonic-sort-cpu.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-data-list-sort:
    main:                try-data-list-sort.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-quick-sort:
    main:                try-quick-sort.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-hello:
    main:                try-hello.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-mandelbrot-hs:
    main:                try-mandelbrot-hs.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-mandelbrot:
    main:                try-mandelbrot.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-mandelbrot-cpu:
    main:                try-mandelbrot-cpu.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-texel-buffer-nega:
    main:                try-texel-buffer-nega.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute

tests:
  try-vulkan-compute-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
