name:                try-vulkan-compute
version:             0.1.0.0
github:              "githubuser/try-vulkan-compute"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-vulkan-compute#readme>

dependencies:
- base >= 4.7 && < 5
- deepseq
- stm
- bytestring
- text
- containers
- parallel
- random
- data-default
- array
- vector
- time
- filepath
- JuicyPixels
- gpu-vulkan
- try-gpu-vulkan-ext-debug-utils
- shaderc
- language-spir-v
- hetero-parameter-list
- storable-generic
- ranged-list
- typelevel-tools-yj
- temporary
- tools-yj

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  c-sources:
    - csrc/hello.c
    - csrc/quicksort.c
    - csrc/bitonicsort.c
    - csrc/mandelbrot.c

data-files:
  - shader/hello.comp
  - shader/hello.spv

executables:
  try-hello-world:
    main:                try-hello-world.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-hello-world-noth:
    main:                try-hello-world-noth.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-hello-world-noth2:
    main:                try-hello-world-noth2.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-push-constant:
    main:                try-push-constant.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-saitan-simple:
    main:                try-saitan-simple.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-bitonic-sort-new:
    main:                try-bitonic-sort-new.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-bitonic-sort-new-test:
    main:                try-bitonic-sort-new-test.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-quick-bitonic-sort:
    main:                try-quick-bitonic-sort.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-hello:
    main:                try-hello.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-mandelbrot-hs:
    main:                try-mandelbrot-hs.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-mandelbrot:
    main:                try-mandelbrot.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-mandelbrot-cpu:
    main:                try-mandelbrot-cpu.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-texel-buffer-nega:
    main:                try-texel-buffer-nega.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
  try-bicubic:
    main:                try-bicubic.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute

tests:
  try-vulkan-compute-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-compute
