name:                try-gzip-yaftee-zlib-ft
version:             0.1.0.0
github:              "YoshikuniJujo/try-gzip-yaftee-zlib-ft"
license:             BSD-3-Clause
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "Copyright (c) 2025 Yoshikuni Jujo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/try-gzip-yaftee-zlib-ft#readme>

dependencies:
- base >= 4.7 && < 5
- deepseq
- primitive
- mono-traversable
- containers
- array
- vector
- bytestring
- directory
- filepath
- union-color
- tools-yj
- typelevel-tools-yj
- yaftee
- yaftee-basic-monads
- yaftee-conduit
- try-yaftee-conduit-mono-traversable
- yaftee-conduit-bytestring
- try-yaftee-conduit-bytestring-ft
- higher-order-open-union
- bytestring-ft
- zlib-yaftee
- zlib-core

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  try-gzip-yaftee-zlib-ft-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-png-decode:
    main:                try-png-decode.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-gzip-deflate:
    main:                try-gzip-deflate.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-zlib-deflate:
    main:                try-zlib-deflate.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-read-chunk:
    main:                try-read-chunk.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-decod-gray:
    main:                try-decod-gray.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-gray-alpha:
    main:                try-gray-alpha.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-palette:
    main:                try-palette.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-apng:
    main:                try-apng.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-apng-codec:
    main:                try-apng-codec.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-apng-to-png:
    main:                try-apng-to-png.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-apng-to-pngs:
    main:                try-apng-to-pngs.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-all-red:
    main:                try-all-red.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-time-gradation:
    main:                try-time-gradation.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-apng-rgba-to-gray:
    main:                try-apng-rgba-to-gray.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-apng-gray-blink:
    main:                try-apng-gray-blink.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-apng-lifegame:
    main:                try-apng-lifegame.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-png-rgba-to-gray:
    main:                try-png-rgba-to-gray.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-png-rgba-to-gray1:
    main:                try-png-rgba-to-gray1.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-apng-lifegame-gray1-nointerlace:
    main:                try-apng-lifegame-gray1-nointerlace.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-apng-lifegame-gray1:
    main:                try-apng-lifegame-gray1.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-lifegame-ng:
    main:                try-lifegame-ng.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-readchunk-ng:
    main:                try-readchunk-ng.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-readchunk-ng-black-on-white:
    main:                try-readchunk-ng-black-on-white.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-decod-lifegame-gray1:
    main:                try-decod-lifegame-gray1.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-apng-lifegame-with-ratio:
    main:                try-apng-lifegame-with-ratio.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-png-glider:
    main:                try-png-glider.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-read-board:
    main:                try-read-board.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-lifegame-ng-remove-glider:
    main:                try-lifegame-ng-remove-glider.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft

tests:
  try-gzip-yaftee-zlib-ft-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
