name:                try-gzip-yaftee-zlib-ft
version:             0.1.0.0
github:              "YoshikuniJujo/try-gzip-yaftee-zlib-ft"
license:             BSD-3-Clause
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "Copyright (c) 2025 Yoshikuni Jujo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/try-gzip-yaftee-zlib-ft#readme>

dependencies:
- base >= 4.7 && < 5
- primitive
- mono-traversable
- bytestring
- union-color
- tools-yj
- typelevel-tools-yj
- try-yaftee
- try-yaftee-basic-monads
- try-yaftee-conduit
- try-yaftee-conduit-mono-traversable
- try-yaftee-conduit-bytestring
- try-yaftee-conduit-bytestring-ft
- try-higher-order-open-union
- try-bytestring-ft
- try-zlib-library
- try-zlib-core

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  try-gzip-yaftee-zlib-ft-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  try-png-decode:
    main:                try-png-decode.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
  for-debug:
    main:                for-debug.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft

tests:
  try-gzip-yaftee-zlib-ft-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gzip-yaftee-zlib-ft
