name:                try-shaderc
version:             0.1.0.5
github:              "githubuser/try-shaderc"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-shaderc#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- bytestring
- mtl
- data-default
- language-spir-v
- nowdoc
- exception-hierarchy
- c-enum
- c-struct
- storable-peek-poke

library:
  source-dirs: src
  pkg-config-dependencies:
  - shaderc
  exposed-modules:
  - Language.SpirV.Shaderc
  - Language.SpirV.Shaderc.TH
  - Language.SpirV.Shaderc.Exception
  - Language.SpirV.Shaderc.Exception.Enum
  - Language.SpirV.Shaderc.CompileOptions

data-files:
- data/ShaderKind.txt

executables:
  try-shaderc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-shaderc

tests:
  try-shaderc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-shaderc
