name:                try-simple-cairo-new
version:             0.1.0.0
github:              "githubuser/try-simple-cairo-new"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-simple-cairo-new#readme>

dependencies:
- base >= 4.7 && < 5
- text
- JuicyPixels
- simple-cairo
- cairo-image
- JuicyCairo
- simple-pango

library:
  source-dirs: src

executables:
  try-simple-cairo-new-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo-new
  try-sloth:
    main:                try-sloth.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo-new
  try-line-join:
    main:                try-line-join.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo-new
  try-fill:
    main:                try-fill.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo-new
  try-porter-duff:
    main:                try-porter-duff.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo-new

tests:
  try-simple-cairo-new-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-simple-cairo-new
