name:                try-vulkan-rectangles
version:             0.1.0.11
github:              "githubuser/try-vulkan-rectangles"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-vulkan-rectangles#readme>

dependencies:
- base >= 4.7 && < 5
- primitive
- stm
- template-haskell
- data-default
- containers
- array
- vector
- text
- JuicyPixels
- union-color
- try-gpu-vulkan
- try-gpu-vulkan-khr
- try-gpu-vulkan-khr-glfw
- try-gpu-vulkan-ext-debug-utils
- try-gpu-vulkan-cglm
- try-shaderc
- try-language-spir-v
- try-hetero-parameter-list
- ranged-list
- try-storable-hetero-list
- try-storable-peek-poke
- try-storable-generic
- typelevel-tools
- try-glfw-group
- GLFW-b
- time
- mtl
- optparse-declarative
- simple-cairo
- cairo-image
- simple-pango
- try-moffy
- try-cairo-image-samples

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  try-multi-rectangles:
    main:                try-multi-rectangles.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-rectangles
  try-multi-rectangles2:
    main:                try-multi-rectangles2.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-rectangles
  try-use-cairo:
    main:                try-use-cairo.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-rectangles

tests:
  try-vulkan-rectangles-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-rectangles
