name:                try-vulkan-middle-khr
version:             0.1.0.1
github:              "YoshikuniJujo/try-vulkan-middle-khr"
license:             BSD3
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "2023 Yoshikuni Jujo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/try-vulkan-middle-khr#readme>

dependencies:
- base >= 4.7 && < 5
- data-default
- text
- c-enum
- try-storable-peek-poke
- try-vulkan-middle
- try-vulkan-core
- try-gpu-vulkan-core-khr-swapchain
- try-gpu-vulkan-core-khr-surface
- typelevel-tools

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  try-vulkan-middle-khr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-vulkan-middle-khr
