-- This file is automatically generated by the tools/makeEnum.hs
--	% stack runghc --cwd tools/ makeEnum

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeSynonymInstances #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-missing-export-lists -fno-warn-tabs #-}

module Gpu.Vulkan.Khr.Surface.Enum where

import Foreign.Storable
import Foreign.C.Enum
import Data.Bits
import Data.Word
import Data.Default

#include <vulkan/vulkan.h>

enum "TransformFlagBits" ''#{type VkSurfaceTransformFlagBitsKHR}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("TransformFlagsZero", 0),
	("TransformIdentityBit",
		#{const VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR}),
	("TransformRotate90Bit",
		#{const VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR}),
	("TransformRotate180Bit",
		#{const VK_SURFACE_TRANSFORM_ROTATE_180_BIT_KHR}),
	("TransformRotate270Bit",
		#{const VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR}),
	("TransformHorizontalMirrorBit",
		#{const VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR}),
	("TransformHorizontalMirrorRotate90Bit",
		#{const VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR}),
	("TransformHorizontalMirrorRotate180Bit",
		#{const VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR}),
	("TransformHorizontalMirrorRotate270Bit",
		#{const VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR}),
	("TransformInheritBit",
		#{const VK_SURFACE_TRANSFORM_INHERIT_BIT_KHR}),
	("TransformFlagBitsMaxEnum",
		#{const VK_SURFACE_TRANSFORM_FLAG_BITS_MAX_ENUM_KHR}) ]

instance Default TransformFlagBits where
	def = TransformFlagsZero

enum "CompositeAlphaFlagBits" ''#{type VkCompositeAlphaFlagBitsKHR}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("CompositeAlphaFlagsZero", 0),
	("CompositeAlphaOpaqueBit",
		#{const VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR}),
	("CompositeAlphaPreMultipliedBit",
		#{const VK_COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR}),
	("CompositeAlphaPostMultipliedBit",
		#{const VK_COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR}),
	("CompositeAlphaInheritBit",
		#{const VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR}),
	("CompositeAlphaFlagBitsMaxEnum",
		#{const VK_COMPOSITE_ALPHA_FLAG_BITS_MAX_ENUM_KHR}) ]

instance Default CompositeAlphaFlagBits where
	def = CompositeAlphaFlagsZero

enum "ColorSpace" ''#{type VkColorSpaceKHR}
		[''Show, ''Eq, ''Storable] [
	("ColorSpaceSrgbNonlinear",
		#{const VK_COLOR_SPACE_SRGB_NONLINEAR_KHR}),
	("ColorSpaceDisplayP3NonlinearExt",
		#{const VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT}),
	("ColorSpaceExtendedSrgbLinearExt",
		#{const VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT}),
	("ColorSpaceDisplayP3LinearExt",
		#{const VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT}),
	("ColorSpaceDciP3NonlinearExt",
		#{const VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT}),
	("ColorSpaceBt709LinearExt", #{const VK_COLOR_SPACE_BT709_LINEAR_EXT}),
	("ColorSpaceBt709NonlinearExt",
		#{const VK_COLOR_SPACE_BT709_NONLINEAR_EXT}),
	("ColorSpaceBt2020LinearExt",
		#{const VK_COLOR_SPACE_BT2020_LINEAR_EXT}),
	("ColorSpaceHdr10St2084Ext", #{const VK_COLOR_SPACE_HDR10_ST2084_EXT}),
	("ColorSpaceDolbyvisionExt", #{const VK_COLOR_SPACE_DOLBYVISION_EXT}),
	("ColorSpaceHdr10HlgExt", #{const VK_COLOR_SPACE_HDR10_HLG_EXT}),
	("ColorSpaceAdobergbLinearExt",
		#{const VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT}),
	("ColorSpaceAdobergbNonlinearExt",
		#{const VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT}),
	("ColorSpacePassThroughExt", #{const VK_COLOR_SPACE_PASS_THROUGH_EXT}),
	("ColorSpaceExtendedSrgbNonlinearExt",
		#{const VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT}),
	("ColorSpaceDisplayNativeAmd",
		#{const VK_COLOR_SPACE_DISPLAY_NATIVE_AMD}),
	("ColorspaceSrgbNonlinear",
		#{const VK_COLORSPACE_SRGB_NONLINEAR_KHR}),
	("ColorSpaceDciP3LinearExt", #{const VK_COLOR_SPACE_DCI_P3_LINEAR_EXT}),
	("ColorSpaceMaxEnum", #{const VK_COLOR_SPACE_MAX_ENUM_KHR}) ]

enum "PresentMode" ''#{type VkPresentModeKHR}
		[''Show, ''Eq, ''Storable] [
	("PresentModeImmediate", #{const VK_PRESENT_MODE_IMMEDIATE_KHR}),
	("PresentModeMailbox", #{const VK_PRESENT_MODE_MAILBOX_KHR}),
	("PresentModeFifo", #{const VK_PRESENT_MODE_FIFO_KHR}),
	("PresentModeFifoRelaxed",
		#{const VK_PRESENT_MODE_FIFO_RELAXED_KHR}),
	("PresentModeSharedDemandRefresh",
		#{const VK_PRESENT_MODE_SHARED_DEMAND_REFRESH_KHR}),
	("PresentModeSharedContinuousRefresh",
		#{const VK_PRESENT_MODE_SHARED_CONTINUOUS_REFRESH_KHR}),
	("PresentModeMaxEnum", #{const VK_PRESENT_MODE_MAX_ENUM_KHR}) ]

type TransformFlags = TransformFlagBits
type CompositeAlphaFlags = CompositeAlphaFlagBits
