name:                hason
version:             0.1.0.0
id:                  hason-0.1.0.0-inplace
key:                 hason-0.1.0.0-inplace
exposed-modules:     Hason Hason.Eval
import-dirs:
    ${pkgroot}/../lib/javascript-ghcjs-ghc-9.12.4-inplace/hason-0.1.0.0-inplace

library-dirs:
    ${pkgroot}/../lib/javascript-ghcjs-ghc-9.12.4-inplace/hason-0.1.0.0-inplace

library-dirs-static:
    ${pkgroot}/../lib/javascript-ghcjs-ghc-9.12.4-inplace/hason-0.1.0.0-inplace

hs-libraries:        HShason-0.1.0.0-inplace
depends:             array-0.5.8.0-inplace base-4.21.2.0-inplace
