-- This file is automatically generated by the tools/makeEnum.hs
--	% stack runghc --cwd tools/ makeEnum

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Vulkan.Device.Queue.Enum where

import Foreign.Storable
import Foreign.C.Enum
import Data.Bits
import Data.Word

#include <vulkan/vulkan.h>

enum "CreateFlagBits" ''#{type VkDeviceQueueCreateFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("CreateFlagsZero", 0),
	("CreateProtectedBit",
		#{const VK_DEVICE_QUEUE_CREATE_PROTECTED_BIT}),
	("CreateFlagBitsMaxEnum",
		#{const VK_DEVICE_QUEUE_CREATE_FLAG_BITS_MAX_ENUM}) ]

type CreateFlags = CreateFlagBits
