name:                try-compile-time-file
version:             0.1.0.0
github:              "githubuser/try-compile-time-file"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-compile-time-file#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell

library:
  source-dirs: src

executables:
  try-compile-time-file-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-compile-time-file

tests:
  try-compile-time-file-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-compile-time-file

data-dir: data
data-files:
- foo.txt
