name:                try-gpu-vulkan-ext-debug-utils
version:             0.1.0.7
github:              "githubuser/try-gpu-vulkan-ext-debug-utils"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-gpu-vulkan-ext-debug-utils#readme>

dependencies:
- base >= 4.7 && < 5
- try-gpu-vulkan
- try-vulkan-middle
- try-vulkan-middle-ext-debug-utils
- try-storable-peek-poke
- typelevel-tools

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Gpu.Vulkan.Ext.DebugUtils
    - Gpu.Vulkan.Ext.DebugUtils.Messenger

tests:
  try-gpu-vulkan-ext-debug-utils-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gpu-vulkan-ext-debug-utils
