name:                try-yaftee-conduit-bytestring
version:             0.1.0.5
github:              "YoshikuniJujo/try-yaftee-conduit-bytestring"
license:             BSD-3-Clause
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "(c) 2025 Yoshikuni Jujo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/try-yaftee-conduit-bytestring#readme>

dependencies:
- base >= 4.7 && < 5
- array
- bytestring
- typelevel-tools-yj
- try-yaftee
- try-yaftee-conduit
- try-yaftee-basic-monads
- try-higher-order-open-union
- try-bitarray-bs

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  try-yaftee-conduit-bytestring-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-yaftee-conduit-bytestring
