name:                try-fingertree-with-range-second
version:             0.1.0.0
github:              "YoshikuniJujo/try-fingertree-with-range-second"
license:             BSD3
author:              "Yoshikuni Jujo"
maintainer:          "PAF01143@nifty.ne.jp"
copyright:           "Yoshikuni Jujo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/try-fingertree-with-range-second#readme>

dependencies:
- base >= 4.7 && < 5
- ghc
- transformers
- monads-tf

library:
  source-dirs: src

executables:
  try-fingertree-with-range-second-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-fingertree-with-range-second

tests:
  try-fingertree-with-range-second-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-fingertree-with-range-second
