-- This file is automatically generated by the tools/makeEnum.hs
--	% stack runghc --cwd tools/ makeEnum

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeSynonymInstances #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Gpu.Vulkan.Ext.DebugUtils.Enum where

import Foreign.Storable
import Foreign.C.Enum
import Data.Bits
import Data.Word

#include <vulkan/vulkan.h>

enum "MessageSeverityFlagBits" ''#{type VkDebugUtilsMessageSeverityFlagBitsEXT}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("MessageSeverityVerboseBit",
		#{const VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT}),
	("MessageSeverityInfoBit",
		#{const VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT}),
	("MessageSeverityWarningBit",
		#{const VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT}),
	("MessageSeverityErrorBit",
		#{const VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT}),
	("MessageSeverityFlagBitsMaxEnum",
		#{const VK_DEBUG_UTILS_MESSAGE_SEVERITY_FLAG_BITS_MAX_ENUM_EXT}) ]

enum "MessageTypeFlagBits" ''#{type VkDebugUtilsMessageTypeFlagBitsEXT}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("MessageTypeGeneralBit",
		#{const VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT}),
	("MessageTypeValidationBit",
		#{const VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT}),
	("MessageTypePerformanceBit",
		#{const VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT}),
	("MessageTypeFlagBitsMaxEnum",
		#{const VK_DEBUG_UTILS_MESSAGE_TYPE_FLAG_BITS_MAX_ENUM_EXT}) ]

type MessageSeverityFlags = MessageSeverityFlagBits
type MessageTypeFlags = MessageTypeFlagBits
