-- This file is automatically generated by the tools/makeEnum.hs
--	% stack runghc --cwd tools/ makeEnum

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeSynonymInstances #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-missing-export-lists -fno-warn-tabs #-}

module Gpu.Vulkan.Pipeline.ShaderStage.Enum where

import Foreign.Storable
import Foreign.C.Enum
import Data.Word
import Data.Bits
import Data.Default

#include <vulkan/vulkan.h>

enum "CreateFlagBits" ''#{type VkPipelineShaderStageCreateFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("CreateFlagsZero", 0),
	("CreateAllowVaryingSubgroupSizeBit",
		#{const VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT}),
	("CreateRequireFullSubgroupsBit",
		#{const VK_PIPELINE_SHADER_STAGE_CREATE_REQUIRE_FULL_SUBGROUPS_BIT}),
	("CreateAllowVaryingSubgroupSizeBitExt",
		#{const VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT}),
	("CreateRequireFullSubgroupsBitExt",
		#{const VK_PIPELINE_SHADER_STAGE_CREATE_REQUIRE_FULL_SUBGROUPS_BIT_EXT}),
	("CreateFlagBitsMaxEnum",
		#{const VK_PIPELINE_SHADER_STAGE_CREATE_FLAG_BITS_MAX_ENUM}) ]

instance Default CreateFlagBits where
	def = CreateFlagsZero

type CreateFlags = CreateFlagBits
