name:                try-use-moffy-vulkan
version:             0.1.0.0
github:              "githubuser/try-use-moffy-vulkan"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-use-moffy-vulkan#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- stm
- mtl
- containers
- optparse-declarative
- data-default
- time
- type-flip
- ranged-list
- try-moffy
- try-gpu-vulkan
- try-gpu-vulkan-cglm
- try-vulkan-rectangles
- try-glfw-group
- x-keysym

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  try-use-moffy-vulkan-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-use-moffy-vulkan
  try-hello-windows:
    main:                try-hello-windows.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-use-moffy-vulkan
  try-multi-rectangles:
    main:                try-multi-rectangles.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-use-moffy-vulkan

tests:
  try-use-moffy-vulkan-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-use-moffy-vulkan
