name:                try-moffy-samples
version:             0.1.0.0
github:              "githubuser/try-moffy-samples"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-moffy-samples#readme>

dependencies:
- base >= 4.7 && < 5
- stm
- transformers
- monads-tf
- containers
- unordered-containers
- bytestring
- text
- time
- process
- random
- aeson
- JuicyPixels
- http-conduit
- c-enum
- c-struct
- exception-hierarchy
- simple-cairo
- cairo-image
- simple-pango
- union-color
- moffy
- extra-data-yj
- type-flip
- type-set

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  include-dirs: include
  c-sources:
  - csrc/tfe.c
  pkg-config-dependencies:
  - gtk4

executables:
  try-moffy-samples-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy-samples
  try-text-view-exe:
    main:                try-text-view.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy-samples
  file-viewer:
    main:                file-viewer.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy-samples
  try-cancellable:
    main:                try-cancellable.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy-samples
  tfe :
    main:                tfe.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy-samples
  try-cairo :
    main:                try-cairo.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy-samples
  try-drawing-area :
    main:                try-drawing-area.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy-samples
  try-clock:
    main:                try-clock.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy-samples
  try-clock-more:
    main:                try-clock-more.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy-samples
  try-mouse-event:
    main:                try-mouse-event.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy-samples
  try-boxes:
    main:                try-boxes.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy-samples
  try-followbox:
    main:                try-followbox.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy-samples

tests:
  try-moffy-samples-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-moffy-samples
