name:                yj-sandbox
version:             0.1.0.0
github:              "YoshikuniJujo/yj-sandbox"
license:             BSD-3-Clause
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "Copyright Yoshikuni Jujo (c) 2024"

extra-doc-files:
- README.md
- CHANGELOG.md

data-files:
- data/foo.txt

# Metadata used when publishing your package
synopsis:            try hackage
category:            Try

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/yj-sandbox#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell < 3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  yj-sandbox-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yj-sandbox

tests:
  yj-sandbox-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yj-sandbox
