name:                try-gpu-vulkan
version:             0.1.0.77
github:              "githubuser/try-gpu-vulkan"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-gpu-vulkan#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- stm
- containers
- bytestring
- mono-traversable
- data-default
- text
- time
- try-vulkan-middle
- try-language-spir-v
- try-storable-peek-poke
- try-storable-hetero-list
- try-hetero-parameter-list
- try-hetero-parameter-list-with-typelevel-tools
- typelevel-tools
- temporary

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - Gpu.Vulkan
  - Gpu.Vulkan.AllocationCallbacks
  - Gpu.Vulkan.AllocationCallbacks.Internal
  - Gpu.Vulkan.Attachment
  - Gpu.Vulkan.Attachment.Enum
  - Gpu.Vulkan.Buffer
  - Gpu.Vulkan.Buffer.Enum
  - Gpu.Vulkan.BufferView
  - Gpu.Vulkan.Cmd
  - Gpu.Vulkan.ColorComponent.Enum
  - Gpu.Vulkan.CommandBuffer
  - Gpu.Vulkan.CommandBuffer.Enum
  - Gpu.Vulkan.CommandPool
  - Gpu.Vulkan.CommandPool.Enum
  - Gpu.Vulkan.Component
  - Gpu.Vulkan.Component.Enum
  - Gpu.Vulkan.Data
  - Gpu.Vulkan.Descriptor
  - Gpu.Vulkan.Descriptor.Enum
  - Gpu.Vulkan.DescriptorPool
  - Gpu.Vulkan.DescriptorPool.Enum
  - Gpu.Vulkan.DescriptorSet
  - Gpu.Vulkan.DescriptorSetLayout
  - Gpu.Vulkan.DescriptorSetLayout.Enum
  - Gpu.Vulkan.DescriptorSetLayout.BindingFlags
  - Gpu.Vulkan.Device
  - Gpu.Vulkan.Device.Internal
  - Gpu.Vulkan.Device.Enum
  - Gpu.Vulkan.Enum
  - Gpu.Vulkan.Exception
  - Gpu.Vulkan.Exception.Enum
  - Gpu.Vulkan.Fence
  - Gpu.Vulkan.Fence.Internal
  - Gpu.Vulkan.Fence.Enum
  - Gpu.Vulkan.Framebuffer
  - Gpu.Vulkan.Framebuffer.Enum
  - Gpu.Vulkan.Image
  - Gpu.Vulkan.Image.Internal
  - Gpu.Vulkan.Image.Enum
  - Gpu.Vulkan.ImageView
  - Gpu.Vulkan.ImageView.Enum
  - Gpu.Vulkan.Instance
  - Gpu.Vulkan.Instance.Internal
  - Gpu.Vulkan.Memory
  - Gpu.Vulkan.Memory.Enum
  - Gpu.Vulkan.Misc
  - Gpu.Vulkan.Object
  - Gpu.Vulkan.Object.Base
  - Gpu.Vulkan.PhysicalDevice
  - Gpu.Vulkan.PhysicalDevice.Enum
  - Gpu.Vulkan.PhysicalDevice.Struct
  - Gpu.Vulkan.Pipeline.ColorBlendAttachment
  - Gpu.Vulkan.Pipeline.ColorBlendState
  - Gpu.Vulkan.Pipeline.Compute
  - Gpu.Vulkan.Pipeline.DepthStencilState
  - Gpu.Vulkan.Pipeline.DynamicState
  - Gpu.Vulkan.Pipeline.Enum
  - Gpu.Vulkan.Pipeline.Graphics
  - Gpu.Vulkan.Pipeline.InputAssemblyState
  - Gpu.Vulkan.Pipeline.MultisampleState
  - Gpu.Vulkan.Pipeline.RasterizationState
  - Gpu.Vulkan.Pipeline.ShaderStage
  - Gpu.Vulkan.Pipeline.ShaderStage.Enum
  - Gpu.Vulkan.Pipeline.TessellationState
  - Gpu.Vulkan.Pipeline.VertexInputState
  - Gpu.Vulkan.Pipeline.ViewportState
  - Gpu.Vulkan.PipelineCache
  - Gpu.Vulkan.PipelineLayout
  - Gpu.Vulkan.PushConstant
  - Gpu.Vulkan.Query
  - Gpu.Vulkan.Query.Enum
  - Gpu.Vulkan.QueryPool
  - Gpu.Vulkan.Queue
  - Gpu.Vulkan.Queue.Enum
  - Gpu.Vulkan.QueueFamily
  - Gpu.Vulkan.RenderPass
  - Gpu.Vulkan.RenderPass.Enum
  - Gpu.Vulkan.Sample
  - Gpu.Vulkan.Sample.Enum
  - Gpu.Vulkan.Sampler
  - Gpu.Vulkan.Sampler.Enum
  - Gpu.Vulkan.Semaphore
  - Gpu.Vulkan.Semaphore.Internal
  - Gpu.Vulkan.ShaderModule
  - Gpu.Vulkan.Subpass
  - Gpu.Vulkan.Subpass.Enum
  - Gpu.Vulkan.TypeEnum
  - Gpu.Vulkan.VertexInput

data-files:
  - th/vkPhysicalDeviceLimits.txt
  - th/vkPhysicalDeviceFeatures.txt
  - th/vkFormat.txt
  - th/vkShaderStageFlagBits.txt

tests:
  try-gpu-vulkan-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-gpu-vulkan
