-- This file is automatically generated by the tools/makeEnum.hs
--	% stack runghc --cwd tools/ makeEnum

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeSynonymInstances #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-missing-export-lists -fno-warn-tabs #-}

module Gpu.Vulkan.DescriptorSetLayout.Enum where

import Foreign.Storable
import Foreign.C.Enum
import Data.Word
import Data.Bits
import Data.Default

#include <vulkan/vulkan.h>

enum "CreateFlagBits" ''#{type VkDescriptorSetLayoutCreateFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("CreateFlagsZero", 0),
	("CreateUpdateAfterBindPoolBit",
		#{const VK_DESCRIPTOR_SET_LAYOUT_CREATE_UPDATE_AFTER_BIND_POOL_BIT}),
	("CreatePushDescriptorBitKhr",
		#{const VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR}),
	("CreateDescriptorBufferBitExt",
		#{const VK_DESCRIPTOR_SET_LAYOUT_CREATE_DESCRIPTOR_BUFFER_BIT_EXT}),
	("CreateEmbeddedImmutableSamplersBitExt",
		#{const VK_DESCRIPTOR_SET_LAYOUT_CREATE_EMBEDDED_IMMUTABLE_SAMPLERS_BIT_EXT}),
	("CreateHostOnlyPoolBitExt",
		#{const VK_DESCRIPTOR_SET_LAYOUT_CREATE_HOST_ONLY_POOL_BIT_EXT}),
	("CreateUpdateAfterBindPoolBitExt",
		#{const VK_DESCRIPTOR_SET_LAYOUT_CREATE_UPDATE_AFTER_BIND_POOL_BIT_EXT}),
	("CreateHostOnlyPoolBitValve",
		#{const VK_DESCRIPTOR_SET_LAYOUT_CREATE_HOST_ONLY_POOL_BIT_VALVE}),
	("CreateFlagBitsMaxEnum",
		#{const VK_DESCRIPTOR_SET_LAYOUT_CREATE_FLAG_BITS_MAX_ENUM}) ]

instance Default CreateFlagBits where
	def = CreateFlagsZero

type CreateFlags = CreateFlagBits
