(define true #t)
(define false #f)
(define nil ())
(define pi 3.141592653589793)
(define (square x) (* x x))
(define (cube x) (* x x x))
(define (identity x) x)
(define (inc x) (+ x 1))
(define (average x y) (/ (+ x y) 2))
