name:                try-use-foo
version:             0.1.0.0
github:              "githubuser/try-use-foo"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-use-foo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  include-dirs: /home/tatsuya/.qiita/include
  extra-lib-dirs: /home/tatsuya/.qiita/lib
  extra-libraries: foo

executables:
  try-use-foo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-use-foo

tests:
  try-use-foo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-use-foo
