-- This file is automatically generated by the tools/makeEnum.hs
--	% stack runghc --cwd tools/ makeEnum

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Vulkan.CullMode.Enum where

import Foreign.Storable
import Foreign.C.Enum
import Data.Bits
import Data.Word

#include <vulkan/vulkan.h>

enum "FlagBits" ''#{type VkCullModeFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("FlagsZero", 0),
	("None", #{const VK_CULL_MODE_NONE}),
	("FrontBit", #{const VK_CULL_MODE_FRONT_BIT}),
	("BackBit", #{const VK_CULL_MODE_BACK_BIT}),
	("FrontAndBack", #{const VK_CULL_MODE_FRONT_AND_BACK}),
	("FlagBitsMaxEnum", #{const VK_CULL_MODE_FLAG_BITS_MAX_ENUM}) ]

type Flags = FlagBits
