-- This file is automatically generated by the tools/makeEnum.hs
--	% stack runghc --cwd tools/ makeEnum

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeSynonymInstances #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-missing-export-lists -fno-warn-tabs #-}

module Gpu.Vulkan.Pipeline.Enum where

import Foreign.Storable
import Foreign.C.Enum
import Data.Bits
import Data.Word
import Data.Default

#include <vulkan/vulkan.h>

enum "BindPoint" ''#{type VkPipelineBindPoint}
		[''Show, ''Storable] [
	("BindPointGraphics", #{const VK_PIPELINE_BIND_POINT_GRAPHICS}),
	("BindPointCompute", #{const VK_PIPELINE_BIND_POINT_COMPUTE}),
	("BindPointRayTracingKhr",
		#{const VK_PIPELINE_BIND_POINT_RAY_TRACING_KHR}),
	("BindPointSubpassShadingHuawei",
		#{const VK_PIPELINE_BIND_POINT_SUBPASS_SHADING_HUAWEI}),
	("BindPointRayTracingNv",
		#{const VK_PIPELINE_BIND_POINT_RAY_TRACING_NV}),
	("BindPointMaxEnum", #{const VK_PIPELINE_BIND_POINT_MAX_ENUM}) ]

enum "StageFlagBits" ''#{type VkPipelineStageFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("StageFlagsZero", 0),
	("StageTopOfPipeBit",
		#{const VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT}),
	("StageDrawIndirectBit",
		#{const VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT}),
	("StageVertexInputBit",
		#{const VK_PIPELINE_STAGE_VERTEX_INPUT_BIT}),
	("StageVertexShaderBit",
		#{const VK_PIPELINE_STAGE_VERTEX_SHADER_BIT}),
	("StageTessellationControlShaderBit",
		#{const VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT}),
	("StageTessellationEvaluationShaderBit",
		#{const VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT}),
	("StageGeometryShaderBit",
		#{const VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT}),
	("StageFragmentShaderBit",
		#{const VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT}),
	("StageEarlyFragmentTestsBit",
		#{const VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT}),
	("StageLateFragmentTestsBit",
		#{const VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT}),
	("StageColorAttachmentOutputBit",
		#{const VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT}),
	("StageComputeShaderBit",
		#{const VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT}),
	("StageTransferBit", #{const VK_PIPELINE_STAGE_TRANSFER_BIT}),
	("StageBottomOfPipeBit",
		#{const VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT}),
	("StageHostBit", #{const VK_PIPELINE_STAGE_HOST_BIT}),
	("StageAllGraphicsBit",
		#{const VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT}),
	("StageAllCommandsBit",
		#{const VK_PIPELINE_STAGE_ALL_COMMANDS_BIT}),
	("StageNone", #{const VK_PIPELINE_STAGE_NONE}),
	("StageTransformFeedbackBitExt",
		#{const VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT}),
	("StageConditionalRenderingBitExt",
		#{const VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT}),
	("StageAccelerationStructureBuildBitKhr",
		#{const VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR}),
	("StageRayTracingShaderBitKhr",
		#{const VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR}),
	("StageFragmentDensityProcessBitExt",
		#{const VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT}),
	("StageFragmentShadingRateAttachmentBitKhr",
		#{const VK_PIPELINE_STAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR}),
	("StageCommandPreprocessBitNv",
		#{const VK_PIPELINE_STAGE_COMMAND_PREPROCESS_BIT_NV}),
	("StageTaskShaderBitExt",
		#{const VK_PIPELINE_STAGE_TASK_SHADER_BIT_EXT}),
	("StageMeshShaderBitExt",
		#{const VK_PIPELINE_STAGE_MESH_SHADER_BIT_EXT}),
	("StageShadingRateImageBitNv",
		#{const VK_PIPELINE_STAGE_SHADING_RATE_IMAGE_BIT_NV}),
	("StageRayTracingShaderBitNv",
		#{const VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_NV}),
	("StageAccelerationStructureBuildBitNv",
		#{const VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_NV}),
	("StageTaskShaderBitNv",
		#{const VK_PIPELINE_STAGE_TASK_SHADER_BIT_NV}),
	("StageMeshShaderBitNv",
		#{const VK_PIPELINE_STAGE_MESH_SHADER_BIT_NV}),
	("StageNoneKhr", #{const VK_PIPELINE_STAGE_NONE_KHR}),
	("StageFlagBitsMaxEnum",
		#{const VK_PIPELINE_STAGE_FLAG_BITS_MAX_ENUM}) ]

instance Default StageFlagBits where
	def = StageFlagsZero

enum "CreateFlagBits" ''#{type VkPipelineCreateFlagBits}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("CreateFlagsZero", 0),
	("CreateDisableOptimizationBit",
		#{const VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT}),
	("CreateAllowDerivativesBit",
		#{const VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT}),
	("CreateDerivativeBit",
		#{const VK_PIPELINE_CREATE_DERIVATIVE_BIT}),
	("CreateViewIndexFromDeviceIndexBit",
		#{const VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT}),
	("CreateDispatchBaseBit",
		#{const VK_PIPELINE_CREATE_DISPATCH_BASE_BIT}),
	("CreateFailOnPipelineCompileRequiredBit",
		#{const VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT}),
	("CreateEarlyReturnOnFailureBit",
		#{const VK_PIPELINE_CREATE_EARLY_RETURN_ON_FAILURE_BIT}),
	("CreateRenderingFragmentShadingRateAttachmentBitKhr",
		#{const VK_PIPELINE_CREATE_RENDERING_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR}),
	("CreateRenderingFragmentDensityMapAttachmentBitExt",
		#{const VK_PIPELINE_CREATE_RENDERING_FRAGMENT_DENSITY_MAP_ATTACHMENT_BIT_EXT}),
	("CreateRayTracingNoNullAnyHitShadersBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_ANY_HIT_SHADERS_BIT_KHR}),
	("CreateRayTracingNoNullClosestHitShadersBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_CLOSEST_HIT_SHADERS_BIT_KHR}),
	("CreateRayTracingNoNullMissShadersBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_MISS_SHADERS_BIT_KHR}),
	("CreateRayTracingNoNullIntersectionShadersBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_INTERSECTION_SHADERS_BIT_KHR}),
	("CreateRayTracingSkipTrianglesBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_SKIP_TRIANGLES_BIT_KHR}),
	("CreateRayTracingSkipAabbsBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_SKIP_AABBS_BIT_KHR}),
	("CreateRayTracingShaderGroupHandleCaptureReplayBitKhr",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_SHADER_GROUP_HANDLE_CAPTURE_REPLAY_BIT_KHR}),
	("CreateDeferCompileBitNv",
		#{const VK_PIPELINE_CREATE_DEFER_COMPILE_BIT_NV}),
	("CreateCaptureStatisticsBitKhr",
		#{const VK_PIPELINE_CREATE_CAPTURE_STATISTICS_BIT_KHR}),
	("CreateCaptureInternalRepresentationsBitKhr",
		#{const VK_PIPELINE_CREATE_CAPTURE_INTERNAL_REPRESENTATIONS_BIT_KHR}),
	("CreateIndirectBindableBitNv",
		#{const VK_PIPELINE_CREATE_INDIRECT_BINDABLE_BIT_NV}),
	("CreateLibraryBitKhr",
		#{const VK_PIPELINE_CREATE_LIBRARY_BIT_KHR}),
	("CreateDescriptorBufferBitExt",
		#{const VK_PIPELINE_CREATE_DESCRIPTOR_BUFFER_BIT_EXT}),
	("CreateRetainLinkTimeOptimizationInfoBitExt",
		#{const VK_PIPELINE_CREATE_RETAIN_LINK_TIME_OPTIMIZATION_INFO_BIT_EXT}),
	("CreateLinkTimeOptimizationBitExt",
		#{const VK_PIPELINE_CREATE_LINK_TIME_OPTIMIZATION_BIT_EXT}),
	("CreateRayTracingAllowMotionBitNv",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_ALLOW_MOTION_BIT_NV}),
	("CreateColorAttachmentFeedbackLoopBitExt",
		#{const VK_PIPELINE_CREATE_COLOR_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT}),
	("CreateDepthStencilAttachmentFeedbackLoopBitExt",
		#{const VK_PIPELINE_CREATE_DEPTH_STENCIL_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT}),
	("CreateRayTracingOpacityMicromapBitExt",
		#{const VK_PIPELINE_CREATE_RAY_TRACING_OPACITY_MICROMAP_BIT_EXT}),
	("CreateNoProtectedAccessBitExt",
		#{const VK_PIPELINE_CREATE_NO_PROTECTED_ACCESS_BIT_EXT}),
	("CreateProtectedAccessOnlyBitExt",
		#{const VK_PIPELINE_CREATE_PROTECTED_ACCESS_ONLY_BIT_EXT}),
	("CreateDispatchBase",
		#{const VK_PIPELINE_CREATE_DISPATCH_BASE}),
	("RasterizationStateCreateFragmentShadingRateAttachmentBitKhr",
		#{const VK_PIPELINE_RASTERIZATION_STATE_CREATE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR}),
	("RasterizationStateCreateFragmentDensityMapAttachmentBitExt",
		#{const VK_PIPELINE_RASTERIZATION_STATE_CREATE_FRAGMENT_DENSITY_MAP_ATTACHMENT_BIT_EXT}),
	("CreateViewIndexFromDeviceIndexBitKhr",
		#{const VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT_KHR}),
	("CreateDispatchBaseKhr",
		#{const VK_PIPELINE_CREATE_DISPATCH_BASE_KHR}),
	("CreateFailOnPipelineCompileRequiredBitExt",
		#{const VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT_EXT}),
	("CreateEarlyReturnOnFailureBitExt",
		#{const VK_PIPELINE_CREATE_EARLY_RETURN_ON_FAILURE_BIT_EXT}),
	("CreateFlagBitsMaxEnum",
		#{const VK_PIPELINE_CREATE_FLAG_BITS_MAX_ENUM}) ]

instance Default CreateFlagBits where
	def = CreateFlagsZero

type StageFlags = StageFlagBits
type CreateFlags = CreateFlagBits
