-- This file is automatically generated by the tools/makeEnum.hs
--	% stack runghc --cwd tools/ makeEnum

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeSynonymInstances #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# OPTIONS_GHC -Wall -fno-warn-tabs #-}

module Gpu.Vulkan.Khr.Surface.Enum where

import Foreign.Storable
import Foreign.C.Enum
import Data.Bits
import Data.Word

#include <vulkan/vulkan.h>

enum "TransformFlagBits" ''#{type VkSurfaceTransformFlagBitsKHR}
		[''Show, ''Eq, ''Storable, ''Bits] [
	("TransformIdentityBit",
		#{const VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR}),
	("TransformRotate90Bit",
		#{const VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR}),
	("TransformRotate180Bit",
		#{const VK_SURFACE_TRANSFORM_ROTATE_180_BIT_KHR}),
	("TransformRotate270Bit",
		#{const VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR}),
	("TransformHorizontalMirrorBit",
		#{const VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR}),
	("TransformHorizontalMirrorRotate90Bit",
		#{const VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR}),
	("TransformHorizontalMirrorRotate180Bit",
		#{const VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR}),
	("TransformHorizontalMirrorRotate270Bit",
		#{const VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR}),
	("TransformInheritBit",
		#{const VK_SURFACE_TRANSFORM_INHERIT_BIT_KHR}),
	("TransformFlagBitsMaxEnum",
		#{const VK_SURFACE_TRANSFORM_FLAG_BITS_MAX_ENUM_KHR}) ]

type TransformFlags = TransformFlagBits
